apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.name" . }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}
