#!/usr/bin/env bash
# Kafka environment variable defaults - KRaft mode only (Kafka 4.0+)
# Copyright Firestream. MIT License.
# This file is sourced, not executed directly

# Base directories - use absolute paths to avoid variable expansion issues with set -u
export KAFKA_BASE_DIR="${KAFKA_BASE_DIR:-/opt/bitnami/kafka}"
export KAFKA_VOLUME_DIR="${KAFKA_VOLUME_DIR:-/bitnami/kafka}"
export KAFKA_DATA_DIR="${KAFKA_DATA_DIR:-/bitnami/kafka/data}"
export KAFKA_CONF_DIR="${KAFKA_CONF_DIR:-/opt/bitnami/kafka/config}"
export KAFKA_MOUNTED_CONF_DIR="${KAFKA_MOUNTED_CONF_DIR:-/bitnami/kafka/config}"
export KAFKA_CONF_FILE="${KAFKA_CONF_FILE:-/opt/bitnami/kafka/config/server.properties}"
export KAFKA_LOG_DIR="${KAFKA_LOG_DIR:-/opt/bitnami/kafka/logs}"
export KAFKA_HOME="${KAFKA_HOME:-/opt/bitnami/kafka}"
export KAFKA_CERTS_DIR="${KAFKA_CERTS_DIR:-/opt/bitnami/kafka/config/certs}"
export KAFKA_TMP_DIR="${KAFKA_TMP_DIR:-/opt/bitnami/kafka/tmp}"
export KAFKA_PID_FILE="${KAFKA_PID_FILE:-/opt/bitnami/kafka/tmp/kafka.pid}"
export KAFKA_INITSCRIPTS_DIR="${KAFKA_INITSCRIPTS_DIR:-/docker-entrypoint-initdb.d}"

# User and group
export KAFKA_DAEMON_USER="${KAFKA_DAEMON_USER:-kafka}"
export KAFKA_DAEMON_GROUP="${KAFKA_DAEMON_GROUP:-kafka}"

# Default ports
export KAFKA_PORT_NUMBER="${KAFKA_PORT_NUMBER:-9092}"
export KAFKA_CONTROLLER_PORT_NUMBER="${KAFKA_CONTROLLER_PORT_NUMBER:-9093}"

# KRaft configuration (required for Kafka 4.0+)
export KAFKA_CFG_NODE_ID="${KAFKA_CFG_NODE_ID:-}"
export KAFKA_CFG_PROCESS_ROLES="${KAFKA_CFG_PROCESS_ROLES:-}"
export KAFKA_CFG_CONTROLLER_QUORUM_VOTERS="${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS:-}"
export KAFKA_CFG_CONTROLLER_LISTENER_NAMES="${KAFKA_CFG_CONTROLLER_LISTENER_NAMES:-CONTROLLER}"
export KAFKA_CLUSTER_ID="${KAFKA_CLUSTER_ID:-}"
export KAFKA_INITIAL_CONTROLLERS="${KAFKA_INITIAL_CONTROLLERS:-}"
export KAFKA_KRAFT_BOOTSTRAP_SCRAM_USERS="${KAFKA_KRAFT_BOOTSTRAP_SCRAM_USERS:-false}"

# Listeners
export KAFKA_CFG_LISTENERS="${KAFKA_CFG_LISTENERS:-}"
export KAFKA_CFG_ADVERTISED_LISTENERS="${KAFKA_CFG_ADVERTISED_LISTENERS:-}"
export KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP="${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP:-}"
export KAFKA_CFG_INTER_BROKER_LISTENER_NAME="${KAFKA_CFG_INTER_BROKER_LISTENER_NAME:-}"
export KAFKA_CLIENT_LISTENER_NAME="${KAFKA_CLIENT_LISTENER_NAME:-CLIENT}"

# SASL configuration
export KAFKA_CFG_SASL_ENABLED_MECHANISMS="${KAFKA_CFG_SASL_ENABLED_MECHANISMS:-}"
export KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL="${KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL:-}"
export KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL="${KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL:-}"

# SASL users and passwords
export KAFKA_CLIENT_USERS="${KAFKA_CLIENT_USERS:-user}"
export KAFKA_CLIENT_PASSWORDS="${KAFKA_CLIENT_PASSWORDS:-}"
export KAFKA_INTER_BROKER_USER="${KAFKA_INTER_BROKER_USER:-}"
export KAFKA_INTER_BROKER_PASSWORD="${KAFKA_INTER_BROKER_PASSWORD:-}"
export KAFKA_CONTROLLER_USER="${KAFKA_CONTROLLER_USER:-}"
export KAFKA_CONTROLLER_PASSWORD="${KAFKA_CONTROLLER_PASSWORD:-}"
export KAFKA_CLIENT_SASL_MECHANISM="${KAFKA_CLIENT_SASL_MECHANISM:-}"

# TLS/SSL configuration
export KAFKA_TLS_TYPE="${KAFKA_TLS_TYPE:-JKS}"
export KAFKA_TLS_CLIENT_AUTH="${KAFKA_TLS_CLIENT_AUTH:-none}"
export KAFKA_TLS_TRUSTSTORE_FILE="${KAFKA_TLS_TRUSTSTORE_FILE:-}"
export KAFKA_CERTIFICATE_PASSWORD="${KAFKA_CERTIFICATE_PASSWORD:-}"

# Dynamic environment variable commands
export KAFKA_NODE_ID_COMMAND="${KAFKA_NODE_ID_COMMAND:-}"
export KAFKA_CONTROLLER_QUORUM_VOTERS_COMMAND="${KAFKA_CONTROLLER_QUORUM_VOTERS_COMMAND:-}"

# Other settings
export KAFKA_INIT_MAX_TIMEOUT="${KAFKA_INIT_MAX_TIMEOUT:-60}"
export KAFKA_CFG_LOG_DIRS="${KAFKA_CFG_LOG_DIRS:-/bitnami/kafka/data}"
export KAFKA_CFG_MAX_REQUEST_SIZE="${KAFKA_CFG_MAX_REQUEST_SIZE:-}"
export KAFKA_CFG_MAX_PARTITION_FETCH_BYTES="${KAFKA_CFG_MAX_PARTITION_FETCH_BYTES:-}"

# Debug mode
export BITNAMI_DEBUG="${BITNAMI_DEBUG:-false}"
