# Redis chart options: `tls.*` (TLS encryption for client connections).
#
# The Bitnami Redis chart's `tls:` block is a flat, file-oriented schema
# (certFilename / certKeyFilename / dhParamsFilename / etc.) that does NOT
# align with the more elaborate `chartTypes.tlsType` (which models cert-manager
# / autoGenerated). So we declare it explicitly here, mirroring postgresql's
# approach.
{ lib, ... }:

let
  inherit (lib) mkOption types;
in {
  options.redis.tls = mkOption {
    default = null;
    description = "Redis TLS configuration";
    type = types.nullOr (types.submodule {
      options = {
        enabled = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable TLS traffic";
        };

        authClients = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Require clients to authenticate";
        };

        autoGenerated = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable autogenerated certificates";
        };

        existingSecret = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Name of the existing secret that contains the TLS certificates";
        };

        certificatesSecret = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "DEPRECATED. Use existingSecret instead.";
        };

        certFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Certificate filename";
        };

        certKeyFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Certificate Key filename";
        };

        certCAFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "CA Certificate filename";
        };

        dhParamsFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "File containing DH params (in order to support DH based ciphers)";
        };
      };
    });
  };
}
