#!/usr/bin/env bash
# Load _FILE variables - compatible with Bitnami pattern
# Copyright Firestream. MIT License.

airflow_env_vars=(
  AIRFLOW_USERNAME
  AIRFLOW_PASSWORD
  AIRFLOW_FIRSTNAME
  AIRFLOW_LASTNAME
  AIRFLOW_EMAIL
  AIRFLOW_COMPONENT_TYPE
  AIRFLOW_EXECUTOR
  AIRFLOW_RAW_FERNET_KEY
  AIRFLOW_FORCE_OVERWRITE_CONF_FILE
  AIRFLOW_FERNET_KEY
  AIRFLOW_WEBSERVER_SECRET_KEY
  AIRFLOW_APISERVER_SECRET_KEY
  AIRFLOW_APISERVER_BASE_URL
  AIRFLOW_APISERVER_HOST
  AIRFLOW_APISERVER_PORT_NUMBER
  AIRFLOW_LOAD_EXAMPLES
  AIRFLOW_HOSTNAME_CALLABLE
  AIRFLOW_POOL_NAME
  AIRFLOW_POOL_SIZE
  AIRFLOW_POOL_DESC
  AIRFLOW_STANDALONE_DAG_PROCESSOR
  AIRFLOW_TRIGGERER_DEFAULT_CAPACITY
  AIRFLOW_WORKER_QUEUE
  AIRFLOW_SKIP_DB_SETUP
  PYTHONPYCACHEPREFIX
  AIRFLOW_DB_MIGRATE_TIMEOUT
  AIRFLOW_ENABLE_HTTPS
  AIRFLOW_EXTERNAL_APISERVER_PORT_NUMBER
  AIRFLOW_DATABASE_HOST
  AIRFLOW_DATABASE_PORT_NUMBER
  AIRFLOW_DATABASE_NAME
  AIRFLOW_DATABASE_USERNAME
  AIRFLOW_DATABASE_PASSWORD
  AIRFLOW_DATABASE_USE_SSL
  AIRFLOW_REDIS_USE_SSL
  REDIS_HOST
  REDIS_PORT_NUMBER
  REDIS_USER
  REDIS_PASSWORD
  REDIS_DATABASE
  AIRFLOW_LDAP_ENABLE
  AIRFLOW_LDAP_URI
  AIRFLOW_LDAP_SEARCH
  AIRFLOW_LDAP_UID_FIELD
  AIRFLOW_LDAP_BIND_USER
  AIRFLOW_LDAP_BIND_PASSWORD
  AIRFLOW_LDAP_USER_REGISTRATION
  AIRFLOW_LDAP_USER_REGISTRATION_ROLE
  AIRFLOW_LDAP_ROLES_MAPPING
  AIRFLOW_LDAP_ROLES_SYNC_AT_LOGIN
  AIRFLOW_LDAP_USE_TLS
  AIRFLOW_LDAP_ALLOW_SELF_SIGNED
  AIRFLOW_LDAP_TLS_CA_CERTIFICATE
)

for env_var in "${airflow_env_vars[@]}"; do
  file_env_var="${env_var}_FILE"
  if [[ -n "${!file_env_var:-}" ]]; then
    if [[ -r "${!file_env_var:-}" ]]; then
      export "${env_var}=$(< "${!file_env_var}")"
      unset "${file_env_var}"
    else
      warn "Skipping export of ${env_var}. ${!file_env_var:-} is not readable."
    fi
  fi
done
unset airflow_env_vars
