//! Container metadata reading and validation
//!
//! Provides functionality for reading and validating the metadata files
//! generated by the Nix module in containers at `/opt/firestream/`.
//!
//! # Metadata Files
//!
//! - `metadata.json` - Container info, build info, package list
//! - `sbom-cyclonedx.json` - CycloneDX 1.5 SBOM
//! - `sbom-spdx.json` - SPDX 2.3 SBOM
//! - `closure.json` - Nix closure tree

pub mod reader;
pub mod validator;

pub use reader::MetadataReader;
pub use validator::{Check, MetadataValidator, ValidationResult};

/// Error type for metadata operations
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("Metadata file not found: {0}")]
    FileNotFound(String),

    #[error("Failed to parse metadata: {0}")]
    ParseError(String),

    #[error("Validation failed: {0}")]
    ValidationFailed(String),

    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),
}
