# Spark chart options: `security.*` (RPC auth, RPC/storage encryption, SSL).
#
# Bitnami's spark chart generates JKS keystore/truststore passwords on
# render (used by spark-submit and the RPC layer). All SSL/JKS-related
# fields are typed; keystorePassword/truststorePassword are passthroughs
# (the chart populates them from a secret).
{ lib, chartTypes, ... }:

let
  t = chartTypes;
  inherit (lib) mkOption types;
in {
  options.spark.security = mkOption {
    default = null;
    description = "Spark security configuration (RPC auth, RPC/storage encryption, SSL)";
    type = types.nullOr (types.submodule {
      freeformType = types.attrsOf types.anything;

      options = {
        passwordsSecretName = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Name of the secret that contains all the passwords (random by default)";
        };

        rpc = mkOption {
          default = null;
          description = "Spark RPC configuration";
          type = types.nullOr (types.submodule {
            options = {
              authenticationEnabled = mkOption {
                type = types.nullOr types.bool;
                default = null;
                description = "Enable RPC authentication";
              };
              encryptionEnabled = mkOption {
                type = types.nullOr types.bool;
                default = null;
                description = "Enable RPC encryption";
              };
            };
          });
        };

        storageEncryptionEnabled = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable local storage encryption";
        };

        certificatesSecretName = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Name of the secret containing the certificates (DEPRECATED; use security.ssl.existingSecret)";
        };

        ssl = mkOption {
          default = null;
          description = "SSL configuration";
          type = types.nullOr (types.submodule {
            freeformType = types.attrsOf types.anything;
            options = {
              enabled = mkOption {
                type = types.nullOr types.bool;
                default = null;
                description = "Enable SSL configuration";
              };
              needClientAuth = mkOption {
                type = types.nullOr types.bool;
                default = null;
                description = "Enable client authentication";
              };
              protocol = mkOption {
                type = types.nullOr types.str;
                default = null;
                description = "SSL protocol (e.g. TLSv1.2)";
              };
              existingSecret = mkOption {
                type = types.nullOr types.str;
                default = null;
                description = "Existing secret containing TLS certificates (spark-keystore.jks / spark-truststore.jks)";
              };
              autoGenerated = mkOption {
                type = types.nullOr types.bool;
                default = null;
                description = "Create self-signed TLS certificates";
              };
              keystorePassword = mkOption {
                type = types.nullOr types.str;
                default = null;
                description = "JKS keystore password";
              };
              truststorePassword = mkOption {
                type = types.nullOr types.str;
                default = null;
                description = "JKS truststore password";
              };
              resourcesPreset = mkOption {
                type = t.resourcesPreset;
                default = null;
                description = "Resource preset (for the init container that generates the JKS files)";
              };
              resources = mkOption {
                type = types.nullOr t.resourceRequirements;
                default = null;
                description = "Resource requirements for the JKS init container";
              };
            };
          });
        };
      };
    });
  };
}
