
controller:
  replicaCount: 5
  # Sets the size of the heap for the Kafka Controller / broker process
  heapOpts: "-Xmx1024m -Xms1024m"
  persistence:
    size: 20Gi


listeners:
  client:
    protocol: "PLAINTEXT"
  controller:
    protocol: "PLAINTEXT"
  interbroker:
    protocol: "PLAINTEXT"
  external:
    protocol: "PLAINTEXT"


#   ## Service parameters
# ##
# service:
#   ## @param service.type Kubernetes Service type
#   ##
#   type: ClusterIP
#   ## @param service.ports.client Kafka svc port for client connections
#   ## @param service.ports.internal Kafka svc port for inter-broker connections
#   ## @param service.ports.external Kafka svc port for external connections
#   ##
#   # ports:
#   #   client: 9092
#   #   internal: 9093
#   #   external: 9094
#   ## @param service.nodePorts.client Node port for the Kafka client connections
#   ## @param service.nodePorts.external Node port for the Kafka external connections
#   ## NOTE: choose port between <30000-32767>
#   ##
#   nodePorts:
#     client: ""
#     external: ""
#   ## @param service.sessionAffinity Control where client requests go, to the same pod or round-robin
#   ## Values: ClientIP or None
#   ## ref: https://kubernetes.io/docs/user-guide/services/
#   ##
#   sessionAffinity: None
#   ## @param service.sessionAffinityConfig Additional settings for the sessionAffinity
#   ## sessionAffinityConfig:
#   ##   clientIP:
#   ##     timeoutSeconds: 300
#   ##
#   sessionAffinityConfig: {}
#   ## @param service.clusterIP Kafka service Cluster IP
#   ## e.g.:
#   ## clusterIP: None
#   ##
#   # clusterIP: "10.96.1.2"
# # zookeeper:
# #   service:
# #     type: ClusterIP
# #     clusterIP: 10.96.1.10

kraft:
  enabled: true

zoopkeeper:
  enabled: false