services:
  devcontainer:
    init: true
    image: firestream:latest
    build:
      context: ../../
      dockerfile: docker/firestream/Dockerfile
      target: devcontainer
      args:
        HOST_DOCKER_GID: ${HOST_DOCKER_GID:-997}
    env_file:
      - ../../etc/.env.example
    volumes:
      # Mount the project directory on the local file system
      - ../..:/workspace

      # Enable Docker-from-Docker
      # This uses the host's Docker Engine through socket mapping and is preferred over Docker-from-Docker for security and latency
      - /var/run/docker.sock:/var/run/docker-host.sock

    # privileged: false
    # security_opt:
    #   - no-new-privileges:true
    command: sleep infinity # Prevents the container from stopping
    # Required for iptables modification that makes K3D accessible via devcontainer
    cap_add:
      - NET_ADMIN
    network_mode: "host" # Enables K3D access from within container

  postgresql:
    image: "postgres"
    restart: always
    env_file:
      - ../../etc/.env.example
    ports:
      - 5432:5432
