# JupyterHub Container Options
# Copyright Firestream. MIT License.
#
# Externalized, declarative configuration for the JupyterHub container, consumed
# by bin/nix/firestream/containers/eval-container.nix. Defaults here are lifted
# VERBATIM from module.nix so that evalContainer's default build is byte-for-byte
# identical to the legacy flake.nix build path.
#
# IMPORTANT: env defaults use a PER-LEAF mkDefault (each value wrapped
# individually). A single mkDefault around the whole attrset would be replaced
# wholesale when a consumer overrides one key, silently dropping siblings.

{ lib, pkgs, ... }:

let
  jupyterhubVersion = "5.3.0";
in
{
  config.jupyterhub = {
    version = lib.mkDefault jupyterhubVersion;

    python = lib.mkDefault pkgs.python312;

    # Paths configuration (Firestream convention)
    # Per-key mkDefault so individual paths can be overridden independently.
    paths = {
      base = lib.mkDefault "/opt/jupyterhub";
      conf = lib.mkDefault "/opt/jupyterhub/config";
      data = lib.mkDefault "/firestream/jupyterhub/data";
      logs = lib.mkDefault "/opt/jupyterhub/logs";
    };

    # Environment variables with defaults
    # CRITICAL: per-leaf mkDefault (wrap each value), NOT a whole-set mkDefault.
    env = builtins.mapAttrs (_: lib.mkDefault) {
      # Paths not auto-generated by defaults.nix
      JUPYTERHUB_CONF_FILE = "/opt/jupyterhub/config/jupyterhub_config.py";
      JUPYTERHUB_TMP_DIR = "/opt/jupyterhub/tmp";
      JUPYTERHUB_PID_FILE = "/opt/jupyterhub/tmp/jupyterhub.pid";
      JUPYTERHUB_LOGS_DIR = "/opt/jupyterhub/logs";  # scripts use LOGS_DIR (plural)
      JUPYTERHUB_LOG_FILE = "/opt/jupyterhub/logs/jupyterhub.log";

      # PAM library preload (Nix has no ldconfig, so ctypes.find_library("pam")
      # returns None. LD_PRELOAD ensures symbols are available via CDLL(None))
      LD_PRELOAD = "${pkgs.linux-pam}/lib/libpam.so";

      # Volume paths
      JUPYTERHUB_VOLUME_DIR = "/firestream/jupyterhub";

      # Port configuration
      JUPYTERHUB_PROXY_PORT_NUMBER = "8000";
      JUPYTERHUB_API_PORT_NUMBER = "8081";

      # Bootstrap configuration
      JUPYTERHUB_SKIP_BOOTSTRAP = "no";

      # Admin credentials
      JUPYTERHUB_USERNAME = "admin";
      JUPYTERHUB_PASSWORD = "admin";

      # Database configuration
      # Default to sqlite so the standalone image runs out of the box; prod /
      # multi-node overrides via env to "postgresql" with HOST/USER/PASSWORD.
      JUPYTERHUB_DATABASE_TYPE = "sqlite";
      JUPYTERHUB_DATABASE_HOST = "postgresql";
      JUPYTERHUB_DATABASE_PORT_NUMBER = "5432";
      JUPYTERHUB_DATABASE_NAME = "jupyterhub";
      JUPYTERHUB_DATABASE_USER = "jupyterhub";
      JUPYTERHUB_DATABASE_PASSWORD = "";

      # Spawner configuration
      JUPYTERHUB_SPAWNER = "localprocess";

      # Authenticator configuration
      JUPYTERHUB_AUTHENTICATOR = "pam";

      # Timeouts
      JUPYTERHUB_DB_WAIT_TIMEOUT = "120";

      # Empty password flag — default to yes for out-of-the-box local/dev/e2e
      # use; production overrides via the standard mkDefault seam.
      ALLOW_EMPTY_PASSWORD = "yes";

      # Debug mode
      BITNAMI_DEBUG = "false";

      # JupyterHub version (for scripts)
      JUPYTERHUB_VERSION = jupyterhubVersion;
    };

    # Variables that support Docker secrets (_FILE suffix).
    # Whole-value mkDefault is correct for lists (replacement semantics).
    envSecrets = lib.mkDefault [
      "JUPYTERHUB_PASSWORD"
      "JUPYTERHUB_DATABASE_PASSWORD"
      "JUPYTERHUB_DATABASE_HOST"
      "JUPYTERHUB_DATABASE_PORT_NUMBER"
      "JUPYTERHUB_DATABASE_NAME"
      "JUPYTERHUB_DATABASE_USER"
      "JUPYTERHUB_USERNAME"
      "JUPYTERHUB_SKIP_BOOTSTRAP"
    ];

    exposedPorts = lib.mkDefault [ 8000 8081 ];

    # Distinct host-port offset (spacing 2000) so all 8 canonical apps can run
    # simultaneously on docker without colliding. jupyterhub=30000.
    #   proxy    8000 -> host 38000
    #   hub      8081 -> host 38081
    #   healthd  9180 -> host 39180
    compose.hostPortOffset = lib.mkDefault 30000;

    # Phase 4: enable in-image firestream-healthd. JupyterHub does not ship
    # a dedicated /health endpoint; /hub/ returns 200 (login) or 302
    # (redirect to login) once the hub process is serving.
    # `JUPYTERHUB_PROXY_PORT_NUMBER` defaults to 8000. We capture the
    # response code without --fail so 3xx is not treated as an error.
    health = {
      enable = lib.mkDefault true;
      readinessCmd = lib.mkDefault
        ''curl -sS -o /dev/null -w '%{http_code}' "http://localhost:''${JUPYTERHUB_PROXY_PORT_NUMBER:-8000}/hub/" | grep -qE '^(200|302)$' '';
    };
  };
}
