# JupyterHub Container Options
# Copyright Firestream. MIT License.
#
# Externalized, declarative configuration for the JupyterHub container, consumed
# by bin/nix/firestream/containers/eval-container.nix. Defaults here are lifted
# VERBATIM from module.nix so that evalContainer's default build is byte-for-byte
# identical to the legacy flake.nix build path.
#
# IMPORTANT: env defaults use a PER-LEAF mkDefault (each value wrapped
# individually). A single mkDefault around the whole attrset would be replaced
# wholesale when a consumer overrides one key, silently dropping siblings.

{ lib, pkgs, ... }:

let
  jupyterhubVersion = "5.3.0";
in
{
  config.jupyterhub = {
    version = lib.mkDefault jupyterhubVersion;

    python = lib.mkDefault pkgs.python312;

    # Paths configuration (Firestream convention)
    # Per-key mkDefault so individual paths can be overridden independently.
    paths = {
      base = lib.mkDefault "/opt/jupyterhub";
      conf = lib.mkDefault "/opt/jupyterhub/config";
      data = lib.mkDefault "/firestream/jupyterhub/data";
      logs = lib.mkDefault "/opt/jupyterhub/logs";
    };

    # Environment variables with defaults
    # CRITICAL: per-leaf mkDefault (wrap each value), NOT a whole-set mkDefault.
    env = builtins.mapAttrs (_: lib.mkDefault) {
      # Paths not auto-generated by defaults.nix
      JUPYTERHUB_CONF_FILE = "/opt/jupyterhub/config/jupyterhub_config.py";
      JUPYTERHUB_TMP_DIR = "/opt/jupyterhub/tmp";
      JUPYTERHUB_PID_FILE = "/opt/jupyterhub/tmp/jupyterhub.pid";
      JUPYTERHUB_LOGS_DIR = "/opt/jupyterhub/logs";  # scripts use LOGS_DIR (plural)
      JUPYTERHUB_LOG_FILE = "/opt/jupyterhub/logs/jupyterhub.log";

      # PAM library preload (Nix has no ldconfig, so ctypes.find_library("pam")
      # returns None. LD_PRELOAD ensures symbols are available via CDLL(None))
      LD_PRELOAD = "${pkgs.linux-pam}/lib/libpam.so";

      # Volume paths
      JUPYTERHUB_VOLUME_DIR = "/firestream/jupyterhub";

      # Port configuration
      JUPYTERHUB_PROXY_PORT_NUMBER = "8000";
      JUPYTERHUB_API_PORT_NUMBER = "8081";

      # Bootstrap configuration
      JUPYTERHUB_SKIP_BOOTSTRAP = "no";

      # Admin credentials
      JUPYTERHUB_USERNAME = "admin";
      JUPYTERHUB_PASSWORD = "admin";

      # Database configuration
      JUPYTERHUB_DATABASE_TYPE = "postgresql";
      JUPYTERHUB_DATABASE_HOST = "postgresql";
      JUPYTERHUB_DATABASE_PORT_NUMBER = "5432";
      JUPYTERHUB_DATABASE_NAME = "jupyterhub";
      JUPYTERHUB_DATABASE_USER = "jupyterhub";
      JUPYTERHUB_DATABASE_PASSWORD = "";

      # Spawner configuration
      JUPYTERHUB_SPAWNER = "localprocess";

      # Authenticator configuration
      JUPYTERHUB_AUTHENTICATOR = "pam";

      # Timeouts
      JUPYTERHUB_DB_WAIT_TIMEOUT = "120";

      # Empty password flag
      ALLOW_EMPTY_PASSWORD = "no";

      # Debug mode
      BITNAMI_DEBUG = "false";

      # JupyterHub version (for scripts)
      JUPYTERHUB_VERSION = jupyterhubVersion;
    };

    # Variables that support Docker secrets (_FILE suffix).
    # Whole-value mkDefault is correct for lists (replacement semantics).
    envSecrets = lib.mkDefault [
      "JUPYTERHUB_PASSWORD"
      "JUPYTERHUB_DATABASE_PASSWORD"
      "JUPYTERHUB_DATABASE_HOST"
      "JUPYTERHUB_DATABASE_PORT_NUMBER"
      "JUPYTERHUB_DATABASE_NAME"
      "JUPYTERHUB_DATABASE_USER"
      "JUPYTERHUB_USERNAME"
      "JUPYTERHUB_SKIP_BOOTSTRAP"
    ];

    exposedPorts = lib.mkDefault [ 8000 8081 ];
  };
}
