#!/bin/bash
# Copyright Firestream. MIT License.
# SPDX-License-Identifier: APACHE-2.0
#
# Configuration script for Apache Spark container
# Generates spark-defaults.conf, spark-env.sh, and metrics.properties
# based on environment variables.
#
# Refactored from Bitnami's libspark.sh for the Firestream module system.

########################
# Generate the base Spark configuration file
# Globals:
#   SPARK_CONF_DIR
# Arguments:
#   None
# Returns:
#   None
#########################
spark_generate_conf_file() {
    info "Generating Spark configuration file..."

    local conf_file="${SPARK_CONF_DIR}/spark-defaults.conf"
    local template_file="${SPARK_CONF_DIR}/spark-defaults.conf.template"

    # Use template if available, otherwise create from scratch
    if [[ -f "$template_file" ]]; then
        cp "$template_file" "$conf_file"
        debug "Created spark-defaults.conf from template"
    else
        # Create minimal default config
        cat > "$conf_file" << 'EOF'
# Spark Configuration
# Generated by Firestream Spark container

# Core settings
spark.master                     spark://localhost:7077
spark.submit.deployMode          client

# UI settings
spark.ui.enabled                 true

# Logging
spark.eventLog.enabled           false
EOF
        debug "Created minimal spark-defaults.conf"
    fi
}

########################
# Set a Spark configuration value
# Globals:
#   SPARK_CONF_DIR
# Arguments:
#   $1 - configuration key
#   $2 - configuration value
# Returns:
#   None
#########################
spark_conf_set() {
    local key="${1:?missing key}"
    local value="${2:-}"

    # Sanitize inputs (escape backslashes and ampersands)
    value="${value//\\/\\\\}"
    value="${value//&/\\&}"

    # Quote empty values
    [[ -z "$value" ]] && value='""'

    echo "$key $value" >> "${SPARK_CONF_DIR}/spark-defaults.conf"
    debug "Set spark config: $key = $value"
}

########################
# Set a metrics configuration value
# Globals:
#   SPARK_CONF_DIR
# Arguments:
#   $1 - configuration key
#   $2 - configuration value
# Returns:
#   None
#########################
spark_metrics_conf_set() {
    local key="${1:?missing key}"
    local value="${2:-}"

    # Sanitize inputs
    value="${value//\\/\\\\}"
    value="${value//&/\\&}"
    value="${value//\?/\\?}"

    [[ -z "$value" ]] && value='""'

    # Replace existing or append
    local metrics_file="${SPARK_CONF_DIR}/metrics.properties"
    if grep -q "^#*\s*${key}" "$metrics_file" 2>/dev/null; then
        sed -i "s|^#*\s*${key}.*|${key}=${value}|" "$metrics_file"
    else
        echo "${key}=${value}" >> "$metrics_file"
    fi
    debug "Set metrics config: $key = $value"
}

########################
# Configure RPC Authentication
# https://spark.apache.org/docs/latest/security.html#authentication
# Globals:
#   SPARK_*
# Arguments:
#   None
# Returns:
#   None
#########################
spark_configure_rpc_authentication() {
    info "Configuring Spark RPC authentication..."

    echo "" >> "${SPARK_CONF_DIR}/spark-defaults.conf"
    echo "# Spark RPC Authentication settings" >> "${SPARK_CONF_DIR}/spark-defaults.conf"

    spark_conf_set "spark.authenticate" "true"
    spark_conf_set "spark.authenticate.secret" "${SPARK_RPC_AUTHENTICATION_SECRET}"
}

########################
# Configure RPC Encryption
# https://spark.apache.org/docs/latest/security.html#encryption
# Globals:
#   SPARK_*
# Arguments:
#   None
# Returns:
#   None
#########################
spark_configure_rpc_encryption() {
    info "Configuring Spark RPC encryption..."

    echo "" >> "${SPARK_CONF_DIR}/spark-defaults.conf"
    echo "# Spark RPC Encryption settings" >> "${SPARK_CONF_DIR}/spark-defaults.conf"

    spark_conf_set "spark.network.crypto.enabled" "true"
    spark_conf_set "spark.network.crypto.keyLength" "128"
}

########################
# Configure Local Storage Encryption
# https://spark.apache.org/docs/latest/security.html#local-storage-encryption
# Globals:
#   SPARK_*
# Arguments:
#   None
# Returns:
#   None
#########################
spark_configure_local_storage_encryption() {
    info "Configuring Spark local storage encryption..."

    echo "" >> "${SPARK_CONF_DIR}/spark-defaults.conf"
    echo "# Spark Local Storage Encryption settings" >> "${SPARK_CONF_DIR}/spark-defaults.conf"

    spark_conf_set "spark.io.encryption.enabled" "true"
    spark_conf_set "spark.io.encryption.keySizeBits" "128"
}

########################
# Configure SSL/TLS
# https://spark.apache.org/docs/latest/security.html#ssl-configuration
# Globals:
#   SPARK_*
# Arguments:
#   None
# Returns:
#   None
#########################
spark_configure_ssl() {
    info "Configuring Spark SSL..."

    echo "" >> "${SPARK_CONF_DIR}/spark-defaults.conf"
    echo "# Spark SSL settings" >> "${SPARK_CONF_DIR}/spark-defaults.conf"

    spark_conf_set "spark.ssl.enabled" "true"

    if [[ -n "${SPARK_WEBUI_SSL_PORT:-}" ]]; then
        spark_conf_set "spark.ssl.standalone.port" "${SPARK_WEBUI_SSL_PORT}"
    fi

    spark_conf_set "spark.ssl.keyPassword" "${SPARK_SSL_KEY_PASSWORD}"
    spark_conf_set "spark.ssl.keyStore" "${SPARK_SSL_KEYSTORE_FILE}"
    spark_conf_set "spark.ssl.keyStorePassword" "${SPARK_SSL_KEYSTORE_PASSWORD}"
    spark_conf_set "spark.ssl.keyStoreType" "JKS"
    spark_conf_set "spark.ssl.protocol" "${SPARK_SSL_PROTOCOL}"

    if is_boolean_yes "${SPARK_SSL_NEED_CLIENT_AUTH:-no}"; then
        spark_conf_set "spark.ssl.needClientAuth" "true"
    fi

    spark_conf_set "spark.ssl.trustStore" "${SPARK_SSL_TRUSTSTORE_FILE}"
    spark_conf_set "spark.ssl.trustStorePassword" "${SPARK_SSL_TRUSTSTORE_PASSWORD}"
    spark_conf_set "spark.ssl.trustStoreType" "JKS"
}

########################
# Configure Prometheus Metrics
# Globals:
#   SPARK_*
# Arguments:
#   None
# Returns:
#   None
#########################
spark_configure_metrics() {
    info "Enabling Spark metrics..."

    local metrics_file="${SPARK_CONF_DIR}/metrics.properties"
    local template_file="${SPARK_CONF_DIR}/metrics.properties.template"

    # Use template if available
    if [[ -f "$template_file" ]]; then
        cp "$template_file" "$metrics_file"
    else
        touch "$metrics_file"
    fi

    # Configure Prometheus servlet
    spark_metrics_conf_set "*.sink.prometheusServlet.class" "org.apache.spark.metrics.sink.PrometheusServlet"
    spark_metrics_conf_set "*.sink.prometheusServlet.path" "/metrics"
    spark_metrics_conf_set "master.sink.prometheusServlet.path" "/metrics"
    spark_metrics_conf_set "applications.sink.prometheusServlet.path" "/metrics"
}

########################
# Generate spark-env.sh
# Creates runtime environment configuration
# Globals:
#   SPARK_*
#   JAVA_HOME
# Arguments:
#   None
# Returns:
#   None
#########################
spark_generate_env_file() {
    info "Generating spark-env.sh..."

    local env_file="${SPARK_CONF_DIR}/spark-env.sh"

    cat > "$env_file" << EOF
#!/bin/bash
# Spark environment configuration
# Generated by Firestream Spark container

# Java settings
export JAVA_HOME="${JAVA_HOME:-/opt/java}"

# Spark paths
export SPARK_HOME="${SPARK_HOME:-/opt/spark}"
export SPARK_CONF_DIR="${SPARK_CONF_DIR:-\${SPARK_HOME}/conf}"
export SPARK_LOG_DIR="${SPARK_LOG_DIR:-\${SPARK_HOME}/logs}"
export SPARK_WORK_DIR="${SPARK_WORK_DIR:-\${SPARK_HOME}/work}"

# PySpark settings
export PYTHONPATH="${PYTHONPATH:-}"
export PYSPARK_PYTHON="${PYSPARK_PYTHON:-python3}"
export PYSPARK_DRIVER_PYTHON="${PYSPARK_DRIVER_PYTHON:-python3}"

# User settings
export SPARK_USER="${SPARK_USER:-spark}"
EOF

    # Add optional Java options
    if [[ -n "${SPARK_JAVA_OPTS:-}" ]]; then
        echo "export SPARK_JAVA_OPTS=\"${SPARK_JAVA_OPTS}\"" >> "$env_file"
    fi

    # Add driver memory if set
    if [[ -n "${SPARK_DRIVER_MEMORY:-}" ]]; then
        echo "export SPARK_DRIVER_MEMORY=\"${SPARK_DRIVER_MEMORY}\"" >> "$env_file"
    fi

    # Add executor memory if set
    if [[ -n "${SPARK_EXECUTOR_MEMORY:-}" ]]; then
        echo "export SPARK_EXECUTOR_MEMORY=\"${SPARK_EXECUTOR_MEMORY}\"" >> "$env_file"
    fi

    chmod +x "$env_file"
    debug "Generated spark-env.sh"
}

########################
# Main configuration function
# Orchestrates all configuration generation
# Globals:
#   SPARK_*
# Arguments:
#   None
# Returns:
#   None
#########################
spark_configure() {
    info "Configuring Apache Spark..."

    # Generate base configuration file
    spark_generate_conf_file

    # Generate spark-env.sh
    spark_generate_env_file

    # Apply security configurations
    if is_boolean_yes "${SPARK_RPC_AUTHENTICATION_ENABLED:-no}"; then
        spark_configure_rpc_authentication

        # RPC encryption requires authentication
        if is_boolean_yes "${SPARK_RPC_ENCRYPTION_ENABLED:-no}"; then
            spark_configure_rpc_encryption
        fi
    fi

    # Local storage encryption
    if is_boolean_yes "${SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED:-no}"; then
        spark_configure_local_storage_encryption
    fi

    # SSL configuration
    if is_boolean_yes "${SPARK_SSL_ENABLED:-no}"; then
        spark_configure_ssl
    fi

    # Metrics configuration
    if is_boolean_yes "${SPARK_METRICS_ENABLED:-false}" || \
       [[ "${SPARK_METRICS_ENABLED:-false}" == "true" ]]; then
        spark_configure_metrics
    fi

    info "Spark configuration complete"
}
