# JupyterHub configuration template
# Generated by Firestream container initialization
#
# This template is processed during container startup.
# Variables with {{VAR_NAME}} syntax are replaced with environment variable values.
#
# Copyright Firestream. Apache-2.0 License.

c = get_config()

# =============================================================================
# Core JupyterHub Settings
# =============================================================================

# Proxy/Hub URLs
c.JupyterHub.bind_url = 'http://:{{JUPYTERHUB_PROXY_PORT_NUMBER}}'
c.JupyterHub.hub_bind_url = 'http://:{{JUPYTERHUB_API_PORT_NUMBER}}'

# Database configuration
c.JupyterHub.db_url = '{{JUPYTERHUB_DATABASE_URL}}'

# Data directory
c.JupyterHub.data_files_path = '{{JUPYTERHUB_DATA_DIR}}'

# Cookie secret file
c.JupyterHub.cookie_secret_file = '{{JUPYTERHUB_DATA_DIR}}/jupyterhub_cookie_secret'

# =============================================================================
# Spawner Configuration
# =============================================================================

# Map spawner type to Python class
# Supported: localprocess, simple, docker, kubernetes
spawner_map = {
    'localprocess': 'jupyterhub.spawner.LocalProcessSpawner',
    'simple': 'jupyterhub.spawner.SimpleLocalProcessSpawner',
    'docker': 'dockerspawner.DockerSpawner',
    'kubernetes': 'kubespawner.KubeSpawner',
}
c.JupyterHub.spawner_class = spawner_map.get('{{JUPYTERHUB_SPAWNER}}', 'jupyterhub.spawner.LocalProcessSpawner')

# =============================================================================
# Authenticator Configuration
# =============================================================================

# Map authenticator type to Python class
# Supported: pam, dummy, oauth, ldap
auth_map = {
    'pam': 'jupyterhub.auth.PAMAuthenticator',
    'dummy': 'jupyterhub.auth.DummyAuthenticator',
    'oauth': 'oauthenticator.generic.GenericOAuthenticator',
    'ldap': 'ldapauthenticator.LDAPAuthenticator',
}
c.JupyterHub.authenticator_class = auth_map.get('{{JUPYTERHUB_AUTHENTICATOR}}', 'jupyterhub.auth.PAMAuthenticator')

# Admin users configuration
import os
admin_user = os.environ.get('JUPYTERHUB_USERNAME', 'user')
c.Authenticator.admin_users = {admin_user}
c.Authenticator.allowed_users = {admin_user}

# =============================================================================
# Logging Configuration
# =============================================================================

# Log level based on debug mode
import os
if os.environ.get('BITNAMI_DEBUG', 'false').lower() == 'true':
    c.JupyterHub.log_level = 'DEBUG'
else:
    c.JupyterHub.log_level = 'INFO'

# =============================================================================
# Security
# =============================================================================

# Trust proxy headers (for reverse proxy setups)
c.JupyterHub.trust_user_provided_tokens = False

# Cookie settings
c.JupyterHub.cookie_max_age_days = 14

# =============================================================================
# SSL Configuration (uncomment and configure for HTTPS)
# =============================================================================

# c.JupyterHub.ssl_key = '/path/to/ssl.key'
# c.JupyterHub.ssl_cert = '/path/to/ssl.crt'

# =============================================================================
# OAuth Configuration (when JUPYTERHUB_AUTHENTICATOR=oauth)
# =============================================================================

if '{{JUPYTERHUB_AUTHENTICATOR}}' == 'oauth':
    c.GenericOAuthenticator.client_id = os.environ.get('JUPYTERHUB_OAUTH_CLIENT_ID', '')
    c.GenericOAuthenticator.client_secret = os.environ.get('JUPYTERHUB_OAUTH_CLIENT_SECRET', '')
    c.GenericOAuthenticator.oauth_callback_url = os.environ.get('JUPYTERHUB_OAUTH_CALLBACK_URL', '')
    c.GenericOAuthenticator.token_url = os.environ.get('JUPYTERHUB_OAUTH_TOKEN_URL', '')
    c.GenericOAuthenticator.authorize_url = os.environ.get('JUPYTERHUB_OAUTH_AUTHORIZE_URL', '')
    c.GenericOAuthenticator.userdata_url = os.environ.get('JUPYTERHUB_OAUTH_USERDATA_URL', '')

# =============================================================================
# LDAP Configuration (when JUPYTERHUB_AUTHENTICATOR=ldap)
# =============================================================================

if '{{JUPYTERHUB_AUTHENTICATOR}}' == 'ldap':
    c.LDAPAuthenticator.server_address = os.environ.get('JUPYTERHUB_LDAP_SERVER', '')
    c.LDAPAuthenticator.bind_dn_template = os.environ.get('JUPYTERHUB_LDAP_BIND_DN', '')
    c.LDAPAuthenticator.user_search_base = os.environ.get('JUPYTERHUB_LDAP_USER_SEARCH_BASE', '')

# =============================================================================
# Kubernetes Spawner Configuration (when JUPYTERHUB_SPAWNER=kubernetes)
# =============================================================================

if '{{JUPYTERHUB_SPAWNER}}' == 'kubernetes':
    c.KubeSpawner.namespace = os.environ.get('JUPYTERHUB_K8S_NAMESPACE', 'default')
    c.KubeSpawner.image = os.environ.get('JUPYTERHUB_K8S_IMAGE', 'jupyter/base-notebook:latest')

    storage_class = os.environ.get('JUPYTERHUB_K8S_STORAGE_CLASS', '')
    if storage_class:
        c.KubeSpawner.storage_class = storage_class
        c.KubeSpawner.storage_capacity = os.environ.get('JUPYTERHUB_K8S_STORAGE_SIZE', '1Gi')
        c.KubeSpawner.storage_pvc_ensure = True

# =============================================================================
# Docker Spawner Configuration (when JUPYTERHUB_SPAWNER=docker)
# =============================================================================

if '{{JUPYTERHUB_SPAWNER}}' == 'docker':
    c.DockerSpawner.image = os.environ.get('JUPYTERHUB_DOCKER_IMAGE', 'jupyter/base-notebook:latest')
    c.DockerSpawner.network_name = os.environ.get('JUPYTERHUB_DOCKER_NETWORK', 'bridge')
    c.DockerSpawner.remove = True  # Remove containers when stopped

# =============================================================================
# Idle Culling (optional - uncomment to enable)
# =============================================================================

# c.JupyterHub.services = [
#     {
#         'name': 'idle-culler',
#         'command': ['python3', '-m', 'jupyterhub_idle_culler', '--timeout=3600'],
#     }
# ]
