# Nginx chart options aggregator
# Copyright Firestream. MIT License.
#
# Consumed as a NixOS module by `evalChart` (modules = [ ./nix/default.nix ]).
# It imports every per-section options module -- each declaring
# `options.nginx.<section>.*` -- and projects the resolved tree into the
# engine-declared `config.nginx.values` attrset that the values.yaml emitter
# serialises.
#
# The nginx chart has a FLAT shape (like nextjs/odoo): the Deployment's pod-spec
# lives at the top level of values.yaml. It bundles NO subcharts -- a reverse
# proxy has no database -- so unlike nextjs there is no postgresql section.
#
# Two sections are this chart's own, with no Bitnami analogue:
#   * `upstreams` (options/upstreams.nix) -- the headline knob, driving the
#     generated `server { }` blocks in the ConfigMap.
#   * `proxy` / `nginxConfig` (options/proxy.nix) -- proxy behaviour and nginx
#     core directives.
#
# ARCHITECTURAL NOTE (docs/firestream-supported-app.md §3): everything Nix emits
# here is a strict SUBSET of the chart's own value surface. The nginx.conf text
# itself is generated by Go templates in ../templates/_helpers.tpl -- Nix never
# synthesises chart templates or YAML manifests.
#
# CRITICAL -- `config` MUST be bound in the signature. `removeAttrs config.nginx
# [ "_meta" "values" ]` strips those engine-declared keys BEFORE the recursive
# null-filter, otherwise `config.nginx.values` would reference itself.
{ lib, config, ... }:

{
  imports = [
    ./options/common.nix
    ./options/global.nix
    ./options/image.nix
    ./options/app.nix
    ./options/service.nix
    ./options/service-account.nix

    # nginx-specific sections
    ./options/proxy.nix
    ./options/upstreams.nix
  ];

  # chart-manifest.json metadata. A proxy is a small, fast rollout with no
  # subchart to wait on and no Jobs, so the timeout is short relative to the
  # data-plane charts.
  config.nginx._meta.deployment = {
    atomic = true;
    wait = true;
    waitForJobs = true;
    timeout = "5m";
    forceUpgrade = false;
    hooksDisabled = false;
    skipCrds = false;
  };

  # dependsOn stays empty ON PURPOSE. nginx must be able to come up BEFORE the
  # applications it fronts: it answers with its own 502 while a backend is
  # absent or rolling, and proxy_pass resolves Service DNS at request time (the
  # Services need not exist at deploy time). Ordering nginx after its upstreams
  # would only make the edge unavailable for longer during a stack deploy.
  config.nginx._meta.lifecycle = {
    dependsOn = [ ];
    lastBreakingVersion = null;
  };

  # Image injection is supplied by the flake-module
  # (nix/flake-modules/charts/nginx.nix); left empty here.
  config.nginx._meta.containerRefs = { };

  # Project the resolved option tree (minus the engine's `_meta`/`values`) into
  # the serialised `values` attrset, stripping null leaves recursively.
  config.nginx.values =
    lib.filterAttrsRecursive (_: v: v != null)
      (builtins.removeAttrs config.nginx [ "_meta" "values" ]);
}
