//! Metadata file reader
//!
//! Reads and parses the container metadata files generated by the Nix module.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use super::Error;

/// Default base path for metadata files in containers
const DEFAULT_METADATA_PATH: &str = "/opt/firestream";

/// Metadata file names
const METADATA_FILE: &str = "metadata.json";
const CYCLONEDX_SBOM_FILE: &str = "sbom-cyclonedx.json";
const SPDX_SBOM_FILE: &str = "sbom-spdx.json";
const CLOSURE_FILE: &str = "closure.json";

/// Container metadata from metadata.json
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContainerMetadata {
    /// Schema version (should be "1.0.0")
    pub schema_version: String,
    /// ISO 8601 timestamp when metadata was generated
    pub generated_at: String,
    /// Container information
    pub container: ContainerInfo,
    /// Build information
    pub build: BuildInfo,
    /// Package list
    pub packages: PackageList,
}

/// Container information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContainerInfo {
    /// Container name
    pub name: String,
    /// Container version
    pub version: String,
    /// Exposed ports
    #[serde(default)]
    pub exposed_ports: Vec<u16>,
    /// Container user
    #[serde(default)]
    pub user: String,
    /// Working directory
    #[serde(default)]
    pub workdir: String,
}

/// Build information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildInfo {
    /// Nix store path of the container
    pub nix_store_path: String,
    /// Nixpkgs revision used for the build
    pub nixpkgs_revision: String,
    /// Flake URI (optional, present if built from a flake)
    #[serde(default)]
    pub flake_uri: Option<String>,
    /// Flake revision (optional, present if built from a flake)
    #[serde(default)]
    pub flake_revision: Option<String>,
    /// ISO 8601 timestamp when the build was performed
    pub build_timestamp: String,
}

/// Package list
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageList {
    /// Total number of packages
    pub total: usize,
    /// List of packages
    pub items: Vec<PackageInfo>,
}

/// Package information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PackageInfo {
    /// Package name
    pub name: String,
    /// Package version (optional)
    #[serde(default)]
    pub version: Option<String>,
    /// Package URL (purl format)
    pub purl: String,
    /// Nix store path
    pub store_path: String,
}

/// Reads container metadata files from the filesystem
pub struct MetadataReader {
    /// Base path where metadata files are located
    base_path: PathBuf,
}

impl MetadataReader {
    /// Create a new MetadataReader with a custom base path
    pub fn new(base_path: impl AsRef<Path>) -> Self {
        Self {
            base_path: base_path.as_ref().to_path_buf(),
        }
    }

    /// Create a MetadataReader using the default container path (/opt/firestream)
    pub fn from_container() -> Self {
        Self::new(DEFAULT_METADATA_PATH)
    }

    /// Get the base path
    pub fn base_path(&self) -> &Path {
        &self.base_path
    }

    /// Read and parse the main metadata.json file
    pub fn read_metadata(&self) -> Result<ContainerMetadata, Error> {
        let path = self.base_path.join(METADATA_FILE);
        let content = std::fs::read_to_string(&path).map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                Error::FileNotFound(path.display().to_string())
            } else {
                Error::Io(e)
            }
        })?;

        serde_json::from_str(&content)
            .map_err(|e| Error::ParseError(format!("Failed to parse {}: {}", METADATA_FILE, e)))
    }

    /// Read the CycloneDX SBOM file as raw JSON
    pub fn read_cyclonedx_sbom(&self) -> Result<serde_json::Value, Error> {
        let path = self.base_path.join(CYCLONEDX_SBOM_FILE);
        let content = std::fs::read_to_string(&path).map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                Error::FileNotFound(path.display().to_string())
            } else {
                Error::Io(e)
            }
        })?;

        serde_json::from_str(&content).map_err(|e| {
            Error::ParseError(format!("Failed to parse {}: {}", CYCLONEDX_SBOM_FILE, e))
        })
    }

    /// Read the SPDX SBOM file as raw JSON
    pub fn read_spdx_sbom(&self) -> Result<serde_json::Value, Error> {
        let path = self.base_path.join(SPDX_SBOM_FILE);
        let content = std::fs::read_to_string(&path).map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                Error::FileNotFound(path.display().to_string())
            } else {
                Error::Io(e)
            }
        })?;

        serde_json::from_str(&content)
            .map_err(|e| Error::ParseError(format!("Failed to parse {}: {}", SPDX_SBOM_FILE, e)))
    }

    /// Read the closure file as raw JSON
    pub fn read_closure(&self) -> Result<serde_json::Value, Error> {
        let path = self.base_path.join(CLOSURE_FILE);
        let content = std::fs::read_to_string(&path).map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                Error::FileNotFound(path.display().to_string())
            } else {
                Error::Io(e)
            }
        })?;

        serde_json::from_str(&content)
            .map_err(|e| Error::ParseError(format!("Failed to parse {}: {}", CLOSURE_FILE, e)))
    }

    /// List all metadata files that exist in the base path
    pub fn list_files(&self) -> Vec<String> {
        let files = [
            METADATA_FILE,
            CYCLONEDX_SBOM_FILE,
            SPDX_SBOM_FILE,
            CLOSURE_FILE,
        ];

        files
            .iter()
            .filter(|f| self.base_path.join(f).exists())
            .map(|f| f.to_string())
            .collect()
    }

    /// Check if a specific metadata file exists
    pub fn file_exists(&self, filename: &str) -> bool {
        self.base_path.join(filename).exists()
    }

    /// Get the full path to a metadata file
    pub fn file_path(&self, filename: &str) -> PathBuf {
        self.base_path.join(filename)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    fn create_test_metadata() -> serde_json::Value {
        serde_json::json!({
            "schema_version": "1.0.0",
            "generated_at": "2024-01-15T10:30:00Z",
            "container": {
                "name": "test-container",
                "version": "1.0.0",
                "exposed_ports": [8080],
                "user": "app",
                "workdir": "/app"
            },
            "build": {
                "nix_store_path": "/nix/store/abc123-test-container",
                "nixpkgs_revision": "abc123def456",
                "flake_uri": "github:example/repo",
                "flake_revision": "def789",
                "build_timestamp": "2024-01-15T10:00:00Z"
            },
            "packages": {
                "total": 2,
                "items": [
                    {
                        "name": "openssl",
                        "version": "3.0.0",
                        "purl": "pkg:nix/openssl@3.0.0",
                        "store_path": "/nix/store/xyz-openssl-3.0.0"
                    },
                    {
                        "name": "zlib",
                        "version": "1.2.13",
                        "purl": "pkg:nix/zlib@1.2.13",
                        "store_path": "/nix/store/xyz-zlib-1.2.13"
                    }
                ]
            }
        })
    }

    #[test]
    fn test_read_metadata() {
        let temp_dir = TempDir::new().unwrap();
        let metadata = create_test_metadata();
        fs::write(
            temp_dir.path().join("metadata.json"),
            serde_json::to_string_pretty(&metadata).unwrap(),
        )
        .unwrap();

        let reader = MetadataReader::new(temp_dir.path());
        let result = reader.read_metadata().unwrap();

        assert_eq!(result.schema_version, "1.0.0");
        assert_eq!(result.container.name, "test-container");
        assert_eq!(result.packages.total, 2);
    }

    #[test]
    fn test_list_files() {
        let temp_dir = TempDir::new().unwrap();

        // Create only some files
        fs::write(temp_dir.path().join("metadata.json"), "{}").unwrap();
        fs::write(temp_dir.path().join("sbom-cyclonedx.json"), "{}").unwrap();

        let reader = MetadataReader::new(temp_dir.path());
        let files = reader.list_files();

        assert_eq!(files.len(), 2);
        assert!(files.contains(&"metadata.json".to_string()));
        assert!(files.contains(&"sbom-cyclonedx.json".to_string()));
    }

    #[test]
    fn test_file_not_found() {
        let temp_dir = TempDir::new().unwrap();
        let reader = MetadataReader::new(temp_dir.path());

        let result = reader.read_metadata();
        assert!(matches!(result, Err(Error::FileNotFound(_))));
    }
}
