version: '3.8'

services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
    command: "sleep infinity"
