# Odoo chart options: `ingress.*`.
#
# Mirrors superset's ingress.nix shape — the Bitnami odoo chart's ingress
# spec is structurally identical (enabled / pathType / apiVersion /
# hostname / ingressClassName / path / annotations / tls / selfSigned /
# extraHosts / extraPaths / extraTls / secrets / extraRules).
{ lib, ... }:

let
  inherit (lib) mkOption types;
in {
  options.odoo.ingress = mkOption {
    default = null;
    description = "Ingress configuration for the Odoo service";
    type = types.nullOr (types.submodule {
      freeformType = types.attrsOf types.anything;

      options = {
        enabled = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable ingress record generation for Odoo";
        };

        pathType = mkOption {
          type = types.nullOr (types.enum [ "ImplementationSpecific" "Exact" "Prefix" ]);
          default = null;
          description = "Ingress path type";
        };

        apiVersion = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Force Ingress API version (auto-detected if not set)";
        };

        hostname = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Default host for the ingress record";
        };

        ingressClassName = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "IngressClass that will implement the Ingress (k8s 1.18+)";
        };

        path = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Default path for the ingress record";
        };

        annotations = mkOption {
          type = types.nullOr (types.attrsOf types.str);
          default = null;
          description = "Additional annotations for the Ingress resource";
        };

        tls = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable TLS configuration for the host defined at ingress.hostname";
        };

        selfSigned = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Create a TLS secret using self-signed certificates generated by Helm";
        };

        extraHosts = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Additional hostname(s) to be covered with the ingress record";
        };

        extraPaths = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Additional arbitrary paths to be added to the ingress under the main host";
        };

        extraTls = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "TLS configuration for additional hostnames covered by this ingress record";
        };

        secrets = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Custom TLS certificates as secrets";
        };

        extraRules = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Additional rules to be covered with this ingress record";
        };
      };
    });
  };
}
