version: "3.7"

services:
  hive_metastore:
    image: hive_metastore:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
  # database:
  #   image: 'postgres:latest'
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
