---
replicaCount: 1

env:
  HIVE_DB_EXTERNAL: "true"
  HIVE_DB_HOST: "hostname:5432"
  HIVE_DB_NAME: metastore_db
  HIVE_DB_USER: michael_scott
  HIVE_DB_PASS: thats-what-she-said
  HIVE_CONF_PARAMS: hive.metastore.event.db.notification.api.auth:false;hadoop.proxyuser.hive.hosts:HS2_HOST;hadoop.proxyuser.hive.groups:*;datanucleus.autoStartMechanism:SchemaTable

service:
  type: clusterIP

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75