# PostgreSQL chart options: `tls.*` (TLS encryption for client connections).
#
# The Bitnami PostgreSQL chart's `tls:` block is a flat, file-oriented schema
# (certFilename / certKeyFilename / etc.) that does NOT align with the more
# elaborate `chartTypes.tlsType` (which models cert-manager / autoGenerated).
# So we declare it explicitly here.
{ lib, ... }:

let
  inherit (lib) mkOption types;
in {
  options.postgresql.tls = mkOption {
    default = null;
    description = "PostgreSQL TLS configuration";
    type = types.nullOr (types.submodule {
      options = {
        enabled = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable TLS traffic support";
        };

        autoGenerated = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Generate automatically self-signed TLS certificates";
        };

        preferServerCiphers = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Whether to use the server's TLS cipher preferences rather than the client's";
        };

        certificatesSecret = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Name of an existing secret that contains the certificates";
        };

        certFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Certificate filename";
        };

        certKeyFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Certificate key filename";
        };

        certCAFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "CA Certificate filename";
        };

        crlFilename = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "File containing a Certificate Revocation List";
        };
      };
    });
  };
}
