// This file is @generated by prost-build.
/// Optional run parameters consumed on stdin in `--output-format json` mode.
/// Every field is optional; empty/zero means "auto-detect / default", matching
/// the CLI flags (mode → CI_MODE, nix_system → NIX_SYSTEM, etc.).
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunRequest {
    /// "check" | "release"
    #[prost(string, tag = "1")]
    pub mode: ::prost::alloc::string::String,
    /// e.g. "x86_64-linux"
    #[prost(string, tag = "2")]
    pub nix_system: ::prost::alloc::string::String,
    /// e.g. "x86_64"
    #[prost(string, tag = "3")]
    pub arch: ::prost::alloc::string::String,
    /// explicit rundir override
    #[prost(string, tag = "4")]
    pub build_output_dir: ::prost::alloc::string::String,
    /// Inline CI profile — the `ci-manifest.json` payload, shipped with the
    /// request instead of resolved from disk. When present it takes precedence
    /// over `--profile` / `FIRESTREAM_CI_PROFILE` / `./ci-manifest.json` /
    /// `/opt/firestream/ci/ci-manifest.json`, so a caller that already holds the
    /// profile (an orchestrator, a remote agent) does not have to materialise a
    /// file on the far side first.
    #[prost(message, optional, tag = "5")]
    pub profile: ::core::option::Option<CiProfile>,
}
/// A declarative string matcher. Every non-empty clause must hold (logical
/// AND); an all-empty matcher matches everything (a catch-all terminal rule).
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Matcher {
    #[prost(string, tag = "1")]
    pub equals: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub prefix: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub suffix: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub contains: ::prost::alloc::string::String,
}
/// Project identity.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiProject {
    /// short slug, e.g. "firestream"
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// e.g. "x86_64-linux"
    #[prost(string, tag = "2")]
    pub nix_system: ::prost::alloc::string::String,
    /// e.g. "x86_64"
    #[prost(string, tag = "3")]
    pub arch: ::prost::alloc::string::String,
    /// default: "<name>-"
    #[prost(string, tag = "4")]
    pub k8s_namespace_prefix: ::prost::alloc::string::String,
}
/// One pipeline phase. `attrs` / `advisory_attrs` are {system}/{arch}/{project}
/// templates. Arch-conditional attr sets are expressed by emitting a
/// system-specific manifest, never by branching in the consumer.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiPhase {
    /// "tidy" | "verify" | "build" | "attest"
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// "required" | "advisory"
    #[prost(string, tag = "2")]
    pub tier: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub depends_on: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// empty = every mode
    #[prost(string, repeated, tag = "4")]
    pub modes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// tier from tier_rules/tier_default
    #[prost(string, repeated, tag = "5")]
    pub attrs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// forced advisory
    #[prost(string, repeated, tag = "6")]
    pub advisory_attrs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// One attr-leaf -> tier classification rule; first match wins.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiTierRule {
    #[prost(message, optional, tag = "1")]
    pub r#match: ::core::option::Option<Matcher>,
    /// "required" | "advisory"
    #[prost(string, tag = "2")]
    pub tier: ::prost::alloc::string::String,
}
/// One build-phase export rule; first match wins. `strip_prefix`/`strip_suffix`
/// produce {stem} from the attr leaf; `dest` expands {leaf}, {stem}, {arch},
/// {system}, {project}.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiExportTarget {
    #[prost(message, optional, tag = "1")]
    pub r#match: ::core::option::Option<Matcher>,
    #[prost(string, tag = "2")]
    pub strip_prefix: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub strip_suffix: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub dest: ::prost::alloc::string::String,
    /// image|container|binary|wasm|sbom|app|nix
    #[prost(string, tag = "5")]
    pub kind: ::prost::alloc::string::String,
}
/// Fallback destination + kind when no export rule matches.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiExportDefault {
    /// default "{leaf}"
    #[prost(string, tag = "1")]
    pub dest: ::prost::alloc::string::String,
    /// default "binary"
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
}
/// An env-var sentinel. Empty `value` means "present with any value"; a
/// non-empty `value` means "present and exactly equal".
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiEnvSentinel {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// Builder-image identity and guards.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiBuilder {
    #[prost(string, tag = "1")]
    pub image_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub base_image: ::prost::alloc::string::String,
    /// 0 => 100 MiB default
    #[prost(uint64, tag = "3")]
    pub min_image_size_bytes: u64,
    /// default: "<project>-ci-"
    #[prost(string, tag = "4")]
    pub container_name_prefix: ::prost::alloc::string::String,
}
/// Native-vs-docker build and cache policy.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CiBuildStrategy {
    /// "auto" | "native" | "docker"
    #[prost(string, tag = "1")]
    pub default: ::prost::alloc::string::String,
    /// e.g. "host-store"
    #[prost(string, tag = "2")]
    pub native_cache: ::prost::alloc::string::String,
    /// {arch}-templated
    #[prost(string, tag = "3")]
    pub docker_cache_volume: ::prost::alloc::string::String,
}
/// The full profile.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CiProfile {
    /// must be 1
    #[prost(uint32, tag = "1")]
    pub schema_version: u32,
    #[prost(message, optional, tag = "2")]
    pub project: ::core::option::Option<CiProject>,
    #[prost(message, repeated, tag = "3")]
    pub phases: ::prost::alloc::vec::Vec<CiPhase>,
    #[prost(message, repeated, tag = "4")]
    pub tier_rules: ::prost::alloc::vec::Vec<CiTierRule>,
    /// "required" | "advisory"
    #[prost(string, tag = "5")]
    pub tier_default: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub export_targets: ::prost::alloc::vec::Vec<CiExportTarget>,
    #[prost(message, optional, tag = "7")]
    pub export_default: ::core::option::Option<CiExportDefault>,
    #[prost(string, repeated, tag = "8")]
    pub passthrough_vars: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "9")]
    pub devshell_sentinels: ::prost::alloc::vec::Vec<CiEnvSentinel>,
    #[prost(message, optional, tag = "10")]
    pub builder: ::core::option::Option<CiBuilder>,
    #[prost(message, optional, tag = "11")]
    pub build_strategy: ::core::option::Option<CiBuildStrategy>,
    #[prost(map = "string, string", tag = "12")]
    pub provenance: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// One streamed event frame. `kind` discriminates; only the fields relevant to
/// that kind are populated. A flat message (no oneof) keeps the JSON trivial to
/// produce and consume on both sides.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// "run_started" | "run_finished"
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    /// run_started + run_finished
    #[prost(string, tag = "2")]
    pub rundir: ::prost::alloc::string::String,
    /// run_started
    #[prost(string, tag = "3")]
    pub mode: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub nix_system: ::prost::alloc::string::String,
    /// run_finished
    ///
    /// "passed" | "failed" | "aborted"
    #[prost(string, tag = "5")]
    pub outcome: ::prost::alloc::string::String,
    /// 0 green, 1 required-failed, 2 advisory-only
    #[prost(int32, tag = "6")]
    pub exit_code: i32,
    /// <rundir>/logs — full per-attr logs to explore
    #[prost(string, tag = "7")]
    pub logs_dir: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "8")]
    pub failed_attrs: ::prost::alloc::vec::Vec<FailedAttr>,
}
/// A CI attr (nix check/build target) that failed, with a concrete path the
/// caller can hand to an agent to dig into the root cause.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(default)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FailedAttr {
    /// "verify" | "build" | "attest"
    #[prost(string, tag = "1")]
    pub phase: ::prost::alloc::string::String,
    /// attr leaf, e.g. "required-rust-fmt"
    #[prost(string, tag = "2")]
    pub attr: ::prost::alloc::string::String,
    /// per-attr result JSON / stderr log under logs/
    #[prost(string, tag = "3")]
    pub detail_path: ::prost::alloc::string::String,
}
