//! firestream-ci "agent mode" wire protocol — typed JSON-over-stdio.
//!
//! The schema of record is `proto/firestream/ci/v1/ci.proto`; the Rust types below are
//! generated from it (committed; regenerate with `--features codegen`). The wire
//! format is **newline-delimited JSON**: one [`Event`] object per line on
//! stdout, an optional [`RunRequest`] line consumed on stdin.
//!
//! This module is self-contained (no core-types dependency) so the crate stays
//! extractable as a standalone tool.

#![allow(clippy::doc_lazy_continuation)]

// @generated by build.rs from proto/firestream/ci/v1/ci.proto
include!("firestream.ci.v1.rs");

use std::io::Write;
use std::path::Path;

/// Event `kind` discriminators (kept here so producers/consumers agree on the
/// string constants without hard-coding literals).
pub mod kind {
    pub const RUN_STARTED: &str = "run_started";
    pub const RUN_FINISHED: &str = "run_finished";
}

impl Event {
    /// The `run_started` frame: emitted once, before the pipeline runs, so a
    /// caller learns the rundir immediately.
    pub fn run_started(rundir: &Path, mode: &str, nix_system: &str) -> Self {
        Event {
            kind: kind::RUN_STARTED.to_string(),
            rundir: rundir.to_string_lossy().into_owned(),
            mode: mode.to_string(),
            nix_system: nix_system.to_string(),
            ..Default::default()
        }
    }

    /// The terminal `run_finished` frame: verdict + the full logs dir + the
    /// failing attrs (each with a concrete path to dig into).
    pub fn run_finished(
        outcome: &str,
        exit_code: i32,
        rundir: &Path,
        logs_dir: &Path,
        failed_attrs: Vec<FailedAttr>,
    ) -> Self {
        Event {
            kind: kind::RUN_FINISHED.to_string(),
            rundir: rundir.to_string_lossy().into_owned(),
            outcome: outcome.to_string(),
            exit_code,
            logs_dir: logs_dir.to_string_lossy().into_owned(),
            failed_attrs,
            ..Default::default()
        }
    }
}

/// Serialize `event` as one JSON line and write it to `w` (flushing). Used to
/// stream frames to stdout in `--output-format json` mode.
pub fn write_frame<W: Write>(w: &mut W, event: &Event) -> std::io::Result<()> {
    let line = serde_json::to_string(event).unwrap_or_else(|_| "{}".to_string());
    w.write_all(line.as_bytes())?;
    w.write_all(b"\n")?;
    w.flush()
}

/// Parse a single `RunRequest` JSON line (e.g. read from stdin). Blank input
/// yields the default request (auto-detect everything).
pub fn parse_request(line: &str) -> Result<RunRequest, serde_json::Error> {
    let line = line.trim();
    if line.is_empty() {
        return Ok(RunRequest::default());
    }
    serde_json::from_str(line)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn run_finished_round_trips_as_one_json_line() {
        let ev = Event::run_finished(
            "failed",
            1,
            Path::new("/b/2026/sha/171"),
            Path::new("/b/2026/sha/171/logs"),
            vec![FailedAttr {
                phase: "verify".into(),
                attr: "required-rust-fmt".into(),
                detail_path: "/b/2026/sha/171/logs/nix-fast-build-verify.required-rust-fmt.json"
                    .into(),
            }],
        );
        let mut buf = Vec::new();
        write_frame(&mut buf, &ev).unwrap();
        // Exactly one newline-terminated line.
        assert_eq!(buf.iter().filter(|&&b| b == b'\n').count(), 1);
        let line = String::from_utf8(buf).unwrap();
        let back: Event = serde_json::from_str(line.trim()).unwrap();
        assert_eq!(back.kind, kind::RUN_FINISHED);
        assert_eq!(back.exit_code, 1);
        assert_eq!(back.failed_attrs.len(), 1);
        assert_eq!(back.failed_attrs[0].attr, "required-rust-fmt");
    }

    #[test]
    fn partial_frame_deserializes_with_serde_default() {
        // A consumer must tolerate frames that omit fields irrelevant to the
        // `kind` (proto3 + serde(default)).
        let back: Event = serde_json::from_str(r#"{"kind":"run_started","rundir":"/r"}"#).unwrap();
        assert_eq!(back.kind, kind::RUN_STARTED);
        assert_eq!(back.rundir, "/r");
        assert_eq!(back.exit_code, 0);
        assert!(back.failed_attrs.is_empty());
    }

    #[test]
    fn blank_request_is_default() {
        assert_eq!(parse_request("   ").unwrap(), RunRequest::default());
    }
}
