# PostgreSQL configuration generation logic
# Copyright Firestream. Apache-2.0 License.
# This file is sourced, not executed directly

info "Generating PostgreSQL configuration..."

########################
# Create postgresql.conf
########################
postgresql_create_config() {
  info "Creating postgresql.conf..."
  cat > "$POSTGRESQL_CONF_FILE" <<EOF
# PostgreSQL configuration file
# Generated by Firestream Nix-based PostgreSQL container

listen_addresses = '*'
port = $POSTGRESQL_PORT_NUMBER
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
max_wal_size = 1GB
min_wal_size = 80MB
log_timezone = 'UTC'
datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'C.UTF-8'
lc_monetary = 'C.UTF-8'
lc_numeric = 'C.UTF-8'
lc_time = 'C.UTF-8'
default_text_search_config = 'pg_catalog.english'
include_dir = 'conf.d'
EOF
}

########################
# Set a property in postgresql.conf
# Arguments:
#   $1 - property name
#   $2 - value
#   $3 - config file (optional, defaults to POSTGRESQL_CONF_FILE)
########################
postgresql_set_property() {
  local property="${1:?missing property}"
  local value="${2:?missing value}"
  local conf_file="${3:-$POSTGRESQL_CONF_FILE}"

  if grep -qE "^#*\s*$property" "$conf_file" 2>/dev/null; then
    replace_in_file "$conf_file" "^#*\s*$property\s*=.*" "$property = '$value'"
  else
    echo "$property = '$value'" >> "$conf_file"
  fi
}

########################
# Create pg_hba.conf with password authentication
########################
postgresql_password_auth_configuration() {
  info "Generating password authentication configuration..."
  cat > "$POSTGRESQL_PGHBA_FILE" <<EOF
host     all             all             0.0.0.0/0               trust
host     all             all             ::/0                    trust
EOF
}

########################
# Create pg_hba.conf with LDAP authentication
########################
postgresql_ldap_auth_configuration() {
  info "Generating LDAP authentication configuration..."
  local ldap_configuration=""

  if [[ -n "$POSTGRESQL_LDAP_URL" ]]; then
    ldap_configuration="ldapurl=\"$POSTGRESQL_LDAP_URL\""
  else
    ldap_configuration="ldapserver=$POSTGRESQL_LDAP_SERVER"
    [[ -n "$POSTGRESQL_LDAP_PREFIX" ]] && ldap_configuration+=" ldapprefix=\"$POSTGRESQL_LDAP_PREFIX\""
    [[ -n "$POSTGRESQL_LDAP_SUFFIX" ]] && ldap_configuration+=" ldapsuffix=\"$POSTGRESQL_LDAP_SUFFIX\""
    [[ -n "$POSTGRESQL_LDAP_PORT" ]] && ldap_configuration+=" ldapport=$POSTGRESQL_LDAP_PORT"
    [[ -n "$POSTGRESQL_LDAP_BASE_DN" ]] && ldap_configuration+=" ldapbasedn=\"$POSTGRESQL_LDAP_BASE_DN\""
    [[ -n "$POSTGRESQL_LDAP_BIND_DN" ]] && ldap_configuration+=" ldapbinddn=\"$POSTGRESQL_LDAP_BIND_DN\""
    [[ -n "$POSTGRESQL_LDAP_BIND_PASSWORD" ]] && ldap_configuration+=" ldapbindpasswd=$POSTGRESQL_LDAP_BIND_PASSWORD"
    [[ -n "$POSTGRESQL_LDAP_SEARCH_ATTR" ]] && ldap_configuration+=" ldapsearchattribute=$POSTGRESQL_LDAP_SEARCH_ATTR"
    [[ -n "$POSTGRESQL_LDAP_SEARCH_FILTER" ]] && ldap_configuration+=" ldapsearchfilter=\"$POSTGRESQL_LDAP_SEARCH_FILTER\""
    [[ -n "$POSTGRESQL_LDAP_TLS" ]] && ldap_configuration+=" ldaptls=$POSTGRESQL_LDAP_TLS"
    [[ -n "$POSTGRESQL_LDAP_SCHEME" ]] && ldap_configuration+=" ldapscheme=$POSTGRESQL_LDAP_SCHEME"
  fi

  cat > "$POSTGRESQL_PGHBA_FILE" <<EOF
host     all             postgres        0.0.0.0/0               trust
host     all             postgres        ::/0                    trust
host     all             all             0.0.0.0/0               ldap $ldap_configuration
host     all             all             ::/0                    ldap $ldap_configuration
EOF
}

########################
# Add local connection entries to pg_hba.conf
########################
postgresql_allow_local_connection() {
  cat >> "$POSTGRESQL_PGHBA_FILE" <<EOF
local    all             all                                     trust
host     all             all        127.0.0.1/32                 trust
host     all             all        ::1/128                      trust
EOF
}

########################
# Add replication entries to pg_hba.conf
########################
postgresql_add_replication_to_pghba() {
  local replication_auth="trust"
  if [[ -n "$POSTGRESQL_REPLICATION_PASSWORD" ]]; then
    replication_auth="md5"
  fi
  cat >> "$POSTGRESQL_PGHBA_FILE" <<EOF
host      replication     all             0.0.0.0/0               $replication_auth
host      replication     all             ::/0                    $replication_auth
EOF
}

########################
# Restrict pg_hba.conf to use md5 instead of trust
########################
postgresql_restrict_pghba() {
  if [[ -n "$POSTGRESQL_PASSWORD" ]]; then
    replace_in_file "$POSTGRESQL_PGHBA_FILE" "trust" "md5"
  fi
}

########################
# Create pg_hba.conf based on configuration
########################
postgresql_create_pghba() {
  info "Creating pg_hba.conf..."
  if is_boolean_yes "$POSTGRESQL_ENABLE_LDAP"; then
    postgresql_ldap_auth_configuration
  else
    postgresql_password_auth_configuration
  fi
  postgresql_allow_local_connection
}

########################
# Configure replication parameters in postgresql.conf
########################
postgresql_configure_replication_parameters() {
  info "Configuring replication parameters..."
  postgresql_set_property "wal_level" "$POSTGRESQL_WAL_LEVEL"
  postgresql_set_property "max_wal_size" "400MB"
  postgresql_set_property "max_wal_senders" "16"
  postgresql_set_property "wal_keep_size" "128MB"
  postgresql_set_property "hot_standby" "on"

  if is_boolean_yes "$POSTGRESQL_REPLICATION_USE_PASSFILE" && [[ ! -f "$POSTGRESQL_REPLICATION_PASSFILE_PATH" ]]; then
    echo "*:*:*:$POSTGRESQL_REPLICATION_USER:$POSTGRESQL_REPLICATION_PASSWORD" > "$POSTGRESQL_REPLICATION_PASSFILE_PATH"
    chmod 600 "$POSTGRESQL_REPLICATION_PASSFILE_PATH"
  fi
}

########################
# Configure synchronous replication
########################
postgresql_configure_synchronous_replication() {
  local replication_nodes=""
  local synchronous_standby_names=""
  info "Configuring synchronous replication..."

  replication_nodes="\"$POSTGRESQL_CLUSTER_APP_NAME\""

  if [[ ${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS:-0} -gt 0 ]]; then
    synchronous_standby_names="$POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS ($replication_nodes)"
    postgresql_set_property "synchronous_commit" "$POSTGRESQL_SYNCHRONOUS_COMMIT_MODE"
    postgresql_set_property "synchronous_standby_names" "$synchronous_standby_names"
  fi
}

########################
# Configure TLS
########################
postgresql_configure_tls() {
  info "Configuring TLS..."
  chmod 600 "$POSTGRESQL_TLS_KEY_FILE" || warn "Could not set permissions on TLS key file"
  postgresql_set_property "ssl" "on"
  ! is_boolean_yes "$POSTGRESQL_TLS_PREFER_SERVER_CIPHERS" && postgresql_set_property "ssl_prefer_server_ciphers" "off"
  [[ -n "$POSTGRESQL_TLS_CA_FILE" ]] && postgresql_set_property "ssl_ca_file" "$POSTGRESQL_TLS_CA_FILE"
  [[ -n "$POSTGRESQL_TLS_CRL_FILE" ]] && postgresql_set_property "ssl_crl_file" "$POSTGRESQL_TLS_CRL_FILE"
  postgresql_set_property "ssl_cert_file" "$POSTGRESQL_TLS_CERT_FILE"
  postgresql_set_property "ssl_key_file" "$POSTGRESQL_TLS_KEY_FILE"
}

########################
# Configure fsync
########################
postgresql_configure_fsync() {
  info "Configuring fsync..."
  postgresql_set_property "fsync" "$POSTGRESQL_FSYNC"
}

########################
# Configure recovery for slave mode
########################
postgresql_configure_recovery() {
  info "Setting up streaming replication slave..."
  local conninfo_password
  if is_boolean_yes "$POSTGRESQL_REPLICATION_USE_PASSFILE"; then
    conninfo_password="passfile=$POSTGRESQL_REPLICATION_PASSFILE_PATH"
  else
    conninfo_password="password=${POSTGRESQL_REPLICATION_PASSWORD//\&/\\&}"
  fi
  postgresql_set_property "primary_conninfo" "host=$POSTGRESQL_MASTER_HOST port=$POSTGRESQL_MASTER_PORT_NUMBER user=$POSTGRESQL_REPLICATION_USER $conninfo_password application_name=$POSTGRESQL_CLUSTER_APP_NAME"
  touch "$POSTGRESQL_DATA_DIR/standby.signal"
}

info "Configuration generation complete"
