#!/usr/bin/env bash
# PostgreSQL environment variable defaults - matching Bitnami exactly
# Copyright Firestream. Apache-2.0 License.

# Base directories
export POSTGRESQL_BASE_DIR="${POSTGRESQL_BASE_DIR:-/opt/firestream/postgresql}"
export POSTGRESQL_VOLUME_DIR="${POSTGRESQL_VOLUME_DIR:-/firestream/postgresql}"
export POSTGRESQL_DATA_DIR="${POSTGRESQL_DATA_DIR:-$POSTGRESQL_VOLUME_DIR/data}"
export POSTGRESQL_CONF_DIR="${POSTGRESQL_CONF_DIR:-$POSTGRESQL_BASE_DIR/conf}"
export POSTGRESQL_MOUNTED_CONF_DIR="${POSTGRESQL_MOUNTED_CONF_DIR:-$POSTGRESQL_VOLUME_DIR/conf}"
export POSTGRESQL_DEFAULT_CONF_DIR="${POSTGRESQL_DEFAULT_CONF_DIR:-$POSTGRESQL_BASE_DIR/conf.default}"
export POSTGRESQL_CONF_FILE="${POSTGRESQL_CONF_FILE:-$POSTGRESQL_CONF_DIR/postgresql.conf}"
export POSTGRESQL_PGHBA_FILE="${POSTGRESQL_PGHBA_FILE:-$POSTGRESQL_CONF_DIR/pg_hba.conf}"
export POSTGRESQL_LOG_DIR="${POSTGRESQL_LOG_DIR:-$POSTGRESQL_BASE_DIR/logs}"
export POSTGRESQL_LOG_FILE="${POSTGRESQL_LOG_FILE:-$POSTGRESQL_LOG_DIR/postgresql.log}"
export POSTGRESQL_TMP_DIR="${POSTGRESQL_TMP_DIR:-$POSTGRESQL_BASE_DIR/tmp}"
export POSTGRESQL_PID_FILE="${POSTGRESQL_PID_FILE:-$POSTGRESQL_TMP_DIR/postgresql.pid}"
export POSTGRESQL_INITSCRIPTS_DIR="${POSTGRESQL_INITSCRIPTS_DIR:-/docker-entrypoint-initdb.d}"
export POSTGRESQL_PREINITSCRIPTS_DIR="${POSTGRESQL_PREINITSCRIPTS_DIR:-/docker-entrypoint-preinitdb.d}"

# User and group
export POSTGRESQL_DAEMON_USER="${POSTGRESQL_DAEMON_USER:-postgres}"
export POSTGRESQL_DAEMON_GROUP="${POSTGRESQL_DAEMON_GROUP:-postgres}"

# Connection settings
export POSTGRESQL_PORT_NUMBER="${POSTGRESQL_PORT_NUMBER:-5432}"
export POSTGRESQL_ALLOW_REMOTE_CONNECTIONS="${POSTGRESQL_ALLOW_REMOTE_CONNECTIONS:-yes}"
export POSTGRESQL_INIT_MAX_TIMEOUT="${POSTGRESQL_INIT_MAX_TIMEOUT:-60}"

# Authentication
export POSTGRESQL_PASSWORD="${POSTGRESQL_PASSWORD:-}"
export POSTGRESQL_USERNAME="${POSTGRESQL_USERNAME:-postgres}"
export POSTGRESQL_DATABASE="${POSTGRESQL_DATABASE:-}"
export POSTGRESQL_POSTGRES_PASSWORD="${POSTGRESQL_POSTGRES_PASSWORD:-}"
export ALLOW_EMPTY_PASSWORD="${ALLOW_EMPTY_PASSWORD:-no}"

# Replication
export POSTGRESQL_REPLICATION_MODE="${POSTGRESQL_REPLICATION_MODE:-}"
export POSTGRESQL_REPLICATION_USER="${POSTGRESQL_REPLICATION_USER:-}"
export POSTGRESQL_REPLICATION_PASSWORD="${POSTGRESQL_REPLICATION_PASSWORD:-}"
export POSTGRESQL_MASTER_HOST="${POSTGRESQL_MASTER_HOST:-}"
export POSTGRESQL_MASTER_PORT_NUMBER="${POSTGRESQL_MASTER_PORT_NUMBER:-5432}"
export POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS="${POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS:-0}"
export POSTGRESQL_SYNCHRONOUS_COMMIT_MODE="${POSTGRESQL_SYNCHRONOUS_COMMIT_MODE:-on}"
export POSTGRESQL_CLUSTER_APP_NAME="${POSTGRESQL_CLUSTER_APP_NAME:-walreceiver}"
export POSTGRESQL_WAL_LEVEL="${POSTGRESQL_WAL_LEVEL:-replica}"
export POSTGRESQL_REPLICATION_USE_PASSFILE="${POSTGRESQL_REPLICATION_USE_PASSFILE:-no}"
export POSTGRESQL_REPLICATION_PASSFILE_PATH="${POSTGRESQL_REPLICATION_PASSFILE_PATH:-$POSTGRESQL_CONF_DIR/.pgpass}"

# TLS
export POSTGRESQL_ENABLE_TLS="${POSTGRESQL_ENABLE_TLS:-no}"
export POSTGRESQL_TLS_CERT_FILE="${POSTGRESQL_TLS_CERT_FILE:-}"
export POSTGRESQL_TLS_KEY_FILE="${POSTGRESQL_TLS_KEY_FILE:-}"
export POSTGRESQL_TLS_CA_FILE="${POSTGRESQL_TLS_CA_FILE:-}"
export POSTGRESQL_TLS_CRL_FILE="${POSTGRESQL_TLS_CRL_FILE:-}"
export POSTGRESQL_TLS_PREFER_SERVER_CIPHERS="${POSTGRESQL_TLS_PREFER_SERVER_CIPHERS:-yes}"

# LDAP
export POSTGRESQL_ENABLE_LDAP="${POSTGRESQL_ENABLE_LDAP:-no}"
export POSTGRESQL_LDAP_URL="${POSTGRESQL_LDAP_URL:-}"
export POSTGRESQL_LDAP_SERVER="${POSTGRESQL_LDAP_SERVER:-}"
export POSTGRESQL_LDAP_PORT="${POSTGRESQL_LDAP_PORT:-}"
export POSTGRESQL_LDAP_PREFIX="${POSTGRESQL_LDAP_PREFIX:-}"
export POSTGRESQL_LDAP_SUFFIX="${POSTGRESQL_LDAP_SUFFIX:-}"
export POSTGRESQL_LDAP_BASE_DN="${POSTGRESQL_LDAP_BASE_DN:-}"
export POSTGRESQL_LDAP_BIND_DN="${POSTGRESQL_LDAP_BIND_DN:-}"
export POSTGRESQL_LDAP_BIND_PASSWORD="${POSTGRESQL_LDAP_BIND_PASSWORD:-}"
export POSTGRESQL_LDAP_SEARCH_ATTR="${POSTGRESQL_LDAP_SEARCH_ATTR:-}"
export POSTGRESQL_LDAP_SEARCH_FILTER="${POSTGRESQL_LDAP_SEARCH_FILTER:-}"
export POSTGRESQL_LDAP_TLS="${POSTGRESQL_LDAP_TLS:-}"
export POSTGRESQL_LDAP_SCHEME="${POSTGRESQL_LDAP_SCHEME:-}"

# Other settings
export POSTGRESQL_SHUTDOWN_MODE="${POSTGRESQL_SHUTDOWN_MODE:-fast}"
export POSTGRESQL_PGCTLTIMEOUT="${POSTGRESQL_PGCTLTIMEOUT:-60}"
export POSTGRESQL_FIRST_BOOT="${POSTGRESQL_FIRST_BOOT:-yes}"
export POSTGRESQL_INITDB_ARGS="${POSTGRESQL_INITDB_ARGS:-}"
export POSTGRESQL_INITDB_WAL_DIR="${POSTGRESQL_INITDB_WAL_DIR:-}"
export POSTGRESQL_SHARED_PRELOAD_LIBRARIES="${POSTGRESQL_SHARED_PRELOAD_LIBRARIES:-}"
export POSTGRESQL_FSYNC="${POSTGRESQL_FSYNC:-on}"
export POSTGRESQL_DEFAULT_TOAST_COMPRESSION="${POSTGRESQL_DEFAULT_TOAST_COMPRESSION:-}"
export POSTGRESQL_PASSWORD_ENCRYPTION="${POSTGRESQL_PASSWORD_ENCRYPTION:-}"

# Debug mode
export BITNAMI_DEBUG="${BITNAMI_DEBUG:-false}"
