use anyhow::Result;
use std::env;
use std::fs;
use std::path::Path;
use walkdir::WalkDir;

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=build.rs");
    
    let out_dir = env::var("OUT_DIR")?;
    let home_dir = env::var("HOME").unwrap_or_else(|_| "/home/firestream".to_string());
    let bitnami_charts_dir = Path::new(&home_dir).join("bitnami-charts").join("bitnami");
    
    if !bitnami_charts_dir.exists() {
        panic!(
            "Bitnami charts directory not found at: {}. \
            Please ensure bitnami-charts are available at $HOME/bitnami-charts",
            bitnami_charts_dir.display()
        );
    }

    // Create a directory in OUT_DIR to store processed charts
    let charts_out_dir = Path::new(&out_dir).join("charts");
    fs::create_dir_all(&charts_out_dir)?;

    // Generate a manifest of available charts
    let mut chart_manifest = Vec::new();

    // Process each chart directory
    for entry in fs::read_dir(&bitnami_charts_dir)? {
        let entry = entry?;
        let path = entry.path();
        
        if path.is_dir() {
            let chart_name = path.file_name()
                .and_then(|n| n.to_str())
                .expect("Invalid chart directory name");
            
            // Skip the common chart as it's a dependency
            if chart_name == "common" {
                continue;
            }
            
            // Check if Chart.yaml exists
            let chart_yaml_path = path.join("Chart.yaml");
            if chart_yaml_path.exists() {
                println!("cargo:rerun-if-changed={}", chart_yaml_path.display());
                
                // Copy the chart directory to OUT_DIR
                copy_chart_dir(&path, &charts_out_dir.join(chart_name))?;
                
                // Add to manifest
                chart_manifest.push(chart_name.to_string());
            }
        }
    }

    // Also copy the common chart as it's a dependency
    let common_chart_src = bitnami_charts_dir.join("common");
    if common_chart_src.exists() {
        copy_chart_dir(&common_chart_src, &charts_out_dir.join("common"))?;
    }

    // Generate Rust code to include the charts
    let manifest_path = Path::new(&out_dir).join("chart_manifest.rs");
    let manifest_content = generate_manifest_code(&chart_manifest);
    fs::write(manifest_path, manifest_content)?;

    Ok(())
}

fn copy_chart_dir(src: &Path, dst: &Path) -> Result<()> {
    fs::create_dir_all(dst)?;
    
    for entry in WalkDir::new(src).min_depth(1) {
        let entry = entry?;
        let path = entry.path();
        let relative_path = path.strip_prefix(src)?;
        let target_path = dst.join(relative_path);
        
        if entry.file_type().is_dir() {
            fs::create_dir_all(&target_path)?;
        } else {
            if let Some(parent) = target_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(path, target_path)?;
        }
    }
    
    Ok(())
}

fn generate_manifest_code(charts: &[String]) -> String {
    let charts_array = charts.iter()
        .map(|c| format!(r#"    "{}","#, c))
        .collect::<Vec<_>>()
        .join("\n");
    
    format!(
        r#"// This file is automatically generated by build.rs
pub const AVAILABLE_CHARTS: &[&str] = &[
{}
];

pub const CHARTS_DIR: include_dir::Dir = include_dir::include_dir!("$OUT_DIR/charts");
"#,
        charts_array
    )
}