#!/bin/bash
# Copyright Firestream. Apache-2.0 License.
# JupyterHub configuration generation
#
# This file is sourced, not executed directly.
# Generates jupyterhub_config.py from template or defaults.

info "Generating JupyterHub configuration..."

# Ensure config directory exists
ensure_dir_exists "$JUPYTERHUB_CONF_DIR"

# Build database URL based on database type
if [[ "${JUPYTERHUB_DATABASE_TYPE:-sqlite}" == "postgresql" ]]; then
    db_url="postgresql://${JUPYTERHUB_DATABASE_USER}:${JUPYTERHUB_DATABASE_PASSWORD}@${JUPYTERHUB_DATABASE_HOST}:${JUPYTERHUB_DATABASE_PORT_NUMBER}/${JUPYTERHUB_DATABASE_NAME}"
else
    db_url="sqlite:///${JUPYTERHUB_DATA_DIR}/jupyterhub.sqlite"
fi

# Determine spawner class
case "${JUPYTERHUB_SPAWNER:-localprocess}" in
    localprocess) spawner_class="jupyterhub.spawner.LocalProcessSpawner" ;;
    docker) spawner_class="dockerspawner.DockerSpawner" ;;
    kubernetes) spawner_class="kubespawner.KubeSpawner" ;;
    simple) spawner_class="jupyterhub.spawner.SimpleLocalProcessSpawner" ;;
    *) spawner_class="jupyterhub.spawner.LocalProcessSpawner" ;;
esac

# Determine authenticator class
case "${JUPYTERHUB_AUTHENTICATOR:-pam}" in
    pam) authenticator_class="jupyterhub.auth.PAMAuthenticator" ;;
    dummy) authenticator_class="jupyterhub.auth.DummyAuthenticator" ;;
    oauth) authenticator_class="oauthenticator.generic.GenericOAuthenticator" ;;
    ldap) authenticator_class="ldapauthenticator.LDAPAuthenticator" ;;
    *) authenticator_class="jupyterhub.auth.PAMAuthenticator" ;;
esac

# Template file location
template_file="/opt/bitnami/scripts/jupyterhub/bitnami-templates/jupyterhub_config.py.tpl"

# Generate configuration file if it doesn't exist or if force overwrite is set
if [[ ! -f "$JUPYTERHUB_CONF_FILE" ]] || is_boolean_yes "${JUPYTERHUB_FORCE_OVERWRITE_CONF:-no}"; then

    # Check for template file first
    if [[ -f "$template_file" ]]; then
        debug "Generating config from template"
        sed \
            -e "s|{{JUPYTERHUB_PROXY_PORT_NUMBER}}|${JUPYTERHUB_PROXY_PORT_NUMBER:-8000}|g" \
            -e "s|{{JUPYTERHUB_API_PORT_NUMBER}}|${JUPYTERHUB_API_PORT_NUMBER:-8081}|g" \
            -e "s|{{JUPYTERHUB_DATABASE_URL}}|${db_url}|g" \
            -e "s|{{JUPYTERHUB_DATA_DIR}}|${JUPYTERHUB_DATA_DIR}|g" \
            -e "s|{{JUPYTERHUB_SPAWNER_CLASS}}|${spawner_class}|g" \
            -e "s|{{JUPYTERHUB_SPAWNER}}|${JUPYTERHUB_SPAWNER:-localprocess}|g" \
            -e "s|{{JUPYTERHUB_AUTHENTICATOR_CLASS}}|${authenticator_class}|g" \
            -e "s|{{JUPYTERHUB_AUTHENTICATOR}}|${JUPYTERHUB_AUTHENTICATOR:-pam}|g" \
            -e "s|{{JUPYTERHUB_USERNAME}}|${JUPYTERHUB_USERNAME:-user}|g" \
            "$template_file" > "$JUPYTERHUB_CONF_FILE"
    else
        debug "Generating default config (no template found)"
        cat > "$JUPYTERHUB_CONF_FILE" <<EOF
# JupyterHub configuration file
# Generated by Firestream container initialization

# Basic configuration
c = get_config()

# Network settings
c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.port = ${JUPYTERHUB_PROXY_PORT_NUMBER:-8000}
c.JupyterHub.hub_port = ${JUPYTERHUB_API_PORT_NUMBER:-8081}

# Database configuration
c.JupyterHub.db_url = '${db_url}'

# Data directory
c.JupyterHub.data_files_path = '${JUPYTERHUB_DATA_DIR}'

# Spawner configuration
c.JupyterHub.spawner_class = '${spawner_class}'

# Authenticator configuration
c.JupyterHub.authenticator_class = '${authenticator_class}'

# Admin users
c.Authenticator.admin_users = {'${JUPYTERHUB_USERNAME:-user}'}

# Logging
c.JupyterHub.log_level = '$(is_boolean_yes "$BITNAMI_DEBUG" && echo 'DEBUG' || echo 'INFO')'

# Cookie secret and proxy auth token
c.JupyterHub.cookie_secret_file = '${JUPYTERHUB_DATA_DIR}/jupyterhub_cookie_secret'
EOF
    fi

    info "Configuration file created: $JUPYTERHUB_CONF_FILE"
else
    info "Using existing configuration file: $JUPYTERHUB_CONF_FILE"
fi

# Save config hash for change detection
save_config_hash "jupyterhub" "$JUPYTERHUB_CONF_FILE"

info "JupyterHub configuration complete"
