# Kafka chart options: `tls.*` (TLS encryption for SSL/SASL_SSL listeners).
#
# Bitnami's tls block is heterogeneous: a flat set of JKS/PEM key-management
# fields PLUS a nested `autoGenerated` cert-manager submodule. We mirror that
# shape directly rather than reusing `chartTypes.tlsType` (which is shaped
# for the airflow tlsType, not kafka).
{ lib, ... }:

let
  inherit (lib) mkOption types;
in {
  options.kafka.tls = mkOption {
    default = null;
    description = "Kafka TLS settings (required for SSL/SASL_SSL listeners)";
    type = types.nullOr (types.submodule {
      freeformType = types.attrsOf types.anything;

      options = {
        type = mkOption {
          type = types.nullOr (types.enum [ "JKS" "PEM" "jks" "pem" ]);
          default = null;
          description = "TLS certificate format (JKS or PEM)";
        };

        pemChainIncluded = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Whether the CA certificate is bundled with the endpoint cert";
        };

        autoGenerated = mkOption {
          default = null;
          description = "Automatic generation of TLS certificates";
          type = types.nullOr (types.submodule {
            freeformType = types.attrsOf types.anything;
            options = {
              enabled = mkOption {
                type = types.nullOr types.bool;
                default = null;
                description = "Enable automatic generation of TLS certificates";
              };

              engine = mkOption {
                type = types.nullOr (types.enum [ "helm" "cert-manager" ]);
                default = null;
                description = "Mechanism to generate certificates";
              };

              customAltNames = mkOption {
                type = types.nullOr (types.listOf types.str);
                default = null;
                description = "Additional SANs for the auto-generated TLS certificates";
              };

              certManager = mkOption {
                default = null;
                description = "cert-manager-specific options";
                type = types.nullOr (types.submodule {
                  freeformType = types.attrsOf types.anything;
                  options = {
                    existingIssuer = mkOption {
                      type = types.nullOr types.str;
                      default = null;
                      description = "Name of an existing Issuer to use";
                    };

                    existingIssuerKind = mkOption {
                      type = types.nullOr types.str;
                      default = null;
                      description = "Existing Issuer kind (defaults to Issuer)";
                    };

                    keyAlgorithm = mkOption {
                      type = types.nullOr types.str;
                      default = null;
                      description = "Key algorithm for the certificates";
                    };

                    keySize = mkOption {
                      type = types.nullOr types.int;
                      default = null;
                      description = "Key size for the certificates";
                    };

                    duration = mkOption {
                      type = types.nullOr types.str;
                      default = null;
                      description = "Certificate duration";
                    };

                    renewBefore = mkOption {
                      type = types.nullOr types.str;
                      default = null;
                      description = "Renewal period for the certificates";
                    };
                  };
                });
              };
            };
          });
        };

        existingSecret = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Name of the existing secret containing the TLS certificates";
        };

        passwordsSecret = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Name of the secret containing JKS/PEM passwords";
        };

        passwordsSecretKeystoreKey = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Secret key from passwordsSecret containing the Keystore password";
        };

        passwordsSecretTruststoreKey = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Secret key from passwordsSecret containing the Truststore password";
        };

        passwordsSecretPemPasswordKey = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Secret key from passwordsSecret containing the PEM key password";
        };

        keystorePassword = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Password to access the JKS keystore";
        };

        truststorePassword = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Password to access the JKS truststore";
        };

        keyPassword = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Password to access the PEM key";
        };

        jksKeystoreKey = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Secret key from existingSecret containing the keystore";
        };

        jksTruststoreSecret = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Name of an existing truststore secret if separate from existingSecret";
        };

        jksTruststoreKey = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Secret key from existingSecret/jksTruststoreSecret containing the truststore";
        };

        endpointIdentificationAlgorithm = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Endpoint identification algorithm (empty disables hostname verification)";
        };

        sslClientAuth = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Default value for the ssl.client.auth Kafka setting";
        };
      };
    });
  };
}
