# Airflow Container Module
# Copyright Firestream. Apache-2.0 License.
#
# This module defines the Airflow container using the Firestream module system.
# It can be imported by both the standalone flake.nix and the root flake.
#
# Usage:
#   airflowModule = import ./module.nix {
#     inherit pkgs lib firestream pythonEnv airflowVersion;
#   };

{ pkgs
, lib
, firestream
, pythonEnv          # The virtual environment from uv2nix
, airflowVersion     # e.g., "3.0.3"
, python ? pkgs.python312
}:

let
  # Read external script files
  envDefaultsScript = builtins.readFile ./scripts/env-defaults.sh;
  validateScript = builtins.readFile ./scripts/validate.sh;
  configScript = builtins.readFile ./scripts/config.sh;
  initScript = builtins.readFile ./scripts/init.sh;
  secretsScript = builtins.readFile ./scripts/secrets.sh;

  # System dependencies that were in Bitnami's Debian packages
  systemDeps = with pkgs; [
    # SSL/TLS
    cacert
    openssl

    # Kerberos
    krb5

    # LDAP
    openldap
    cyrus_sasl

    # Database clients
    postgresql
    mariadb-connector-c

    # Compression
    bzip2
    xz
    zlib

    # Version control
    git
    openssh

    # Process management
    procps

    # Utilities
    coreutils
    gnugrep
    gnused
    gawk
    findutils
    which
    curl
    wget
    netcat-gnu

    # Terminal
    ncurses
    readline

    # INI file manipulation
    crudini
  ];

  # Runtime binaries needed by Airflow for PATH injection
  runtimeBinDeps = with pkgs; [
    postgresql       # psql client for DB operations
    git              # For DAG sync from git repos
    coreutils
    gnugrep
    gnused
    findutils
    curl
    netcat-gnu
    openssh          # For SSH operators
    crudini          # For INI file manipulation
  ];

  # Compute site packages path
  pythonSitePackages = "${pythonEnv}/${python.sitePackages}";

  # Custom wait-for-port script
  waitForPort = pkgs.writeShellScriptBin "wait-for-port" ''
    #!/usr/bin/env bash
    set -e

    usage() {
      echo "Usage: $0 <host> <port> [timeout]"
      echo "Wait for a TCP port to be available"
      exit 1
    }

    [[ $# -lt 2 ]] && usage

    host="$1"
    port="$2"
    timeout="''${3:-60}"
    elapsed=0

    echo "Waiting for $host:$port to be available (timeout: $timeout seconds)..."

    while ! ${pkgs.netcat-gnu}/bin/nc -z "$host" "$port" 2>/dev/null; do
      if [[ $elapsed -ge $timeout ]]; then
        echo "Timeout waiting for $host:$port"
        exit 1
      fi
      sleep 1
      ((elapsed++))
    done

    echo "$host:$port is available!"
  '';

  # Environment defaults script
  envDefaults = pkgs.writeTextDir "lib/airflow-env-defaults.sh" envDefaultsScript;

  # Secrets loader script
  loadEnvFiles = pkgs.writeTextDir "lib/airflow-load-env-files.sh" secretsScript;

  # Core library functions incorporating Firestream modules + Airflow-specific
  libFunctions = pkgs.writeTextDir "lib/airflow-functions.sh" ''
    #!/usr/bin/env bash
    # Airflow library functions - generated by Nix
    # Copyright Firestream. Apache-2.0 License.

    # Include Firestream core libraries
    ${firestream.allFunctions}

    # Airflow-specific helper: get major version
    airflow_major_version() {
      local raw_version
      raw_version="$(airflow version 2>/dev/null | grep -E -v 'WARNING|DEBUG' || echo "3.0.0")"
      echo "''${raw_version%%.*}"
    }

    # Airflow-specific helper: configure function wrapper
    airflow_configure() {
      ${configScript}
    }

    # Validation function
    airflow_validate() {
      local error_code=0

      print_validation_error() {
        error "$1"
        error_code=1
      }

      info "Validating Airflow configuration..."
      ${validateScript}

      return $error_code
    }

    # Initialization function
    airflow_initialize() {
      ${initScript}
    }
  '';

  # Main entrypoint script
  entrypointScript = pkgs.writeScript "airflow-entrypoint-unwrapped" ''
    #!${pkgs.bashInteractive}/bin/bash
    set -euo pipefail

    # 1. Load environment defaults
    source ${envDefaults}/lib/airflow-env-defaults.sh

    # 2. Load _FILE variables (Docker secrets)
    source ${loadEnvFiles}/lib/airflow-load-env-files.sh

    # 3. Load library functions
    source ${libFunctions}/lib/airflow-functions.sh

    info "Firestream Airflow Container Starting"
    info "Component: ''${AIRFLOW_COMPONENT_TYPE:-api-server}"

    # 4. Validate configuration
    if ! airflow_validate; then
      error "Configuration validation failed"
      exit 1
    fi

    # 5. Install custom requirements if present
    if [[ -f "/bitnami/python/requirements.txt" ]]; then
      info "Installing custom Python requirements..."
      pip install --quiet -r /bitnami/python/requirements.txt || warn "Some requirements failed to install"
    fi

    # 6. Initialize Airflow
    airflow_initialize

    # 7. Determine command based on component type and Airflow version
    major_version=$(airflow_major_version)

    case "$AIRFLOW_COMPONENT_TYPE" in
      api-server)
        if [[ $major_version -eq 2 ]]; then
          cmd=(airflow webserver)
        else
          cmd=(airflow api-server)
        fi
        ;;
      webserver)
        cmd=(airflow webserver)
        ;;
      scheduler)
        cmd=(airflow scheduler)
        ;;
      triggerer)
        cmd=(airflow triggerer)
        ;;
      dag-processor)
        cmd=(airflow dag-processor)
        ;;
      worker)
        cmd=(airflow celery worker)
        [[ -n "''${AIRFLOW_WORKER_QUEUE:-}" ]] && cmd+=(-q "$AIRFLOW_WORKER_QUEUE")
        ;;
      *)
        error "Unknown component: $AIRFLOW_COMPONENT_TYPE"
        exit 1
        ;;
    esac

    # Add PID file
    cmd+=(--pid "''${AIRFLOW_TMP_DIR}/airflow-''${AIRFLOW_COMPONENT_TYPE}.pid")

    # 8. Execute
    info "Starting: ''${cmd[*]}"
    exec "''${cmd[@]}"
  '';

  # Wrapped entrypoint with full PATH injection
  entrypoint = pkgs.runCommand "airflow-entrypoint" {
    nativeBuildInputs = [ pkgs.makeWrapper ];
  } ''
    mkdir -p $out/bin
    makeWrapper ${entrypointScript} $out/bin/airflow-entrypoint \
      --set PATH "${lib.makeBinPath (runtimeBinDeps ++ [ pythonEnv waitForPort ])}" \
      --set PYTHONPATH "${pythonSitePackages}" \
      --set LD_LIBRARY_PATH "${lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib ]}" \
      --set SSL_CERT_FILE "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt" \
      --set NIX_SSL_CERT_FILE "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
  '';

  # Unified runtime environment
  runtimeEnv = pkgs.buildEnv {
    name = "airflow-runtime-env";
    paths = runtimeBinDeps ++ [
      pythonEnv
      entrypoint
      waitForPort
      pkgs.crudini
      envDefaults
      loadEnvFiles
      libFunctions
      pkgs.bashInteractive
      pkgs.cacert
      pkgs.stdenv.cc.cc.lib
    ];
    pathsToLink = [ "/bin" "/lib" "/lib64" "/share" "/etc" ];
  };

  # Docker image definition
  dockerImage = pkgs.dockerTools.buildLayeredImage {
    name = "firestream-airflow";
    tag = "${airflowVersion}-nix";

    contents = pkgs.buildEnv {
      name = "airflow-root";
      paths = systemDeps ++ [
        pythonEnv
        waitForPort
        pkgs.crudini
        libFunctions
        envDefaults
        loadEnvFiles
        entrypoint
        pkgs.bashInteractive
        pkgs.cacert
        pkgs.stdenv.cc.cc.lib
      ];
      pathsToLink = [ "/bin" "/lib" "/lib64" "/share" ];
    };

    config = {
      Env = [
        "PATH=${pythonEnv}/bin:/bin:/usr/bin"
        "AIRFLOW_HOME=/opt/airflow"
        "PYTHONPATH=${pythonSitePackages}"
        "LD_LIBRARY_PATH=/lib:/lib64:${pkgs.stdenv.cc.cc.lib}/lib"
        "SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
        "NIX_SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt"
      ];

      WorkingDir = "/opt/airflow";

      Entrypoint = [ "${entrypoint}/bin/airflow-entrypoint" ];

      ExposedPorts = {
        "8080/tcp" = {};  # Webserver/API
        "8125/tcp" = {};  # StatsD
        "8793/tcp" = {};  # Triggerer
        "8794/tcp" = {};  # Additional services
      };

      User = "1001:1001";

      Volumes = {
        "/opt/airflow/dags" = {};
        "/opt/airflow/logs" = {};
        "/opt/airflow/plugins" = {};
        "/bitnami/python" = {};  # For custom requirements
      };
    };
  };

  # Development shell
  devShell = pkgs.mkShell {
    buildInputs = systemDeps ++ [
      pythonEnv
      waitForPort
      pkgs.crudini
      pkgs.uv
      pkgs.docker
      pkgs.docker-compose
    ];

    shellHook = ''
      echo "Firestream Airflow Nix Development Environment"
      echo "Python: ${python}/bin/python"
      echo "Airflow Version: ${airflowVersion}"
      echo ""
      echo "Available commands:"
      echo "  nix build .#dockerImage    - Build the Docker image"
      echo "  nix develop               - Enter development shell"
      echo "  uv sync                   - Sync Python dependencies"
      echo ""
      export PYTHONPATH="${pythonSitePackages}"
    '';
  };

in {
  # Metadata
  meta = {
    name = "airflow";
    version = airflowVersion;
    description = "Firestream Airflow container module";
    maintainer = "Firestream Contributors";
    license = "Apache-2.0";
    pythonVersion = python.version;
  };

  # All runtime dependencies
  runtimeDeps = systemDeps ++ runtimeBinDeps ++ [ pythonEnv ];

  # Generated scripts
  scripts = {
    inherit envDefaults loadEnvFiles libFunctions entrypoint;
    waitForPort = waitForPort;
  };

  # Complete runtime environment
  inherit runtimeEnv;

  # Docker image
  inherit dockerImage;

  # Development shell
  inherit devShell;

  # Python environment
  inherit pythonEnv python pythonSitePackages;

  # Original configuration (for introspection)
  config = {
    inherit airflowVersion systemDeps runtimeBinDeps;
    exposedPorts = [ 8080 8125 8793 8794 ];
    volumes = [ "/opt/airflow/dags" "/opt/airflow/logs" "/opt/airflow/plugins" "/bitnami/python" ];
  };
}
