# Superset chart options: `ingress.*` (top-level Ingress for the web service).
#
# Superset's top-level ingress resource targets the `web` service. We re-use
# chartTypes.ingressType when it shapes well; otherwise rely on freeform
# passthrough for cert-manager / TLS / extraHosts / extraRules.
{ lib, ... }:

let
  inherit (lib) mkOption types;
in {
  options.superset.ingress = mkOption {
    default = null;
    description = "Ingress configuration for the Superset web service";
    type = types.nullOr (types.submodule {
      freeformType = types.attrsOf types.anything;

      options = {
        enabled = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable ingress record generation for Superset";
        };

        pathType = mkOption {
          type = types.nullOr (types.enum [ "ImplementationSpecific" "Exact" "Prefix" ]);
          default = null;
          description = "Ingress path type";
        };

        apiVersion = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Force Ingress API version (auto-detected if not set)";
        };

        hostname = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Default host for the ingress record";
        };

        ingressClassName = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "IngressClass that will implement the Ingress (k8s 1.18+)";
        };

        path = mkOption {
          type = types.nullOr types.str;
          default = null;
          description = "Default path for the ingress record";
        };

        annotations = mkOption {
          type = types.nullOr (types.attrsOf types.str);
          default = null;
          description = "Additional annotations for the Ingress resource";
        };

        tls = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Enable TLS configuration for ingress.hostname";
        };

        selfSigned = mkOption {
          type = types.nullOr types.bool;
          default = null;
          description = "Create a TLS secret using self-signed certificates generated by Helm";
        };

        extraHosts = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Additional hostname(s) covered by the ingress record";
        };

        extraPaths = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Additional arbitrary paths under the main host";
        };

        extraTls = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "TLS configuration for additional hostnames";
        };

        secrets = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Custom TLS certificates as secrets";
        };

        extraRules = mkOption {
          type = types.nullOr (types.listOf types.attrs);
          default = null;
          description = "Additional rules to be covered with this ingress record";
        };
      };
    });
  };
}
