name: Continuous Testing

on:
  push:
    branches:
      - staging
      - dependabot/**
      - dev
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  # DOCKER_HOST: tcp://localhost:2375
  # BRANCH_ENV: ${{ env.BRANCH }}

jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Containers
        run: |
          make build

      - name: Test
        run: |
          make test

      # - name: Deploy
      #   run: |
      #     make test

      - name: Stop containers
        if: always()
        run: docker kill $(docker ps -q)