name: Continuous Testing

on:
  push:
    branches:
      - staging
      - dependabot/**
      - dev
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  # GIT_COMMIT_HASH: ${{ github.sha }}
  BRANCH_ENV: ${{ env.BRANCH }}

jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make Space
        run: |
            # Remove the "tools" that Github Actions bundles in every image
            sudo rm -rf "/usr/local/share/boost"
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Run Tests
        run: |
            make test

      - name: Build Containers
        run: |
          make build

      - name: Stop containers
        if: always()
        run: docker kill $(docker ps -q)